CenterForOpenScience/ember-osf

tests/dummy/app/controllers/nodes/index.js
tests/dummy/app/templates/nodes/index.hbs

Implementation of creating a node view node model ` createRecord ` and `save()`, for testing.

Create Node ability on dummy

---

tests/dummy/app/router.js
tests/dummy/app/routes/profile.js
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/profile.hbs

https://openscience.atlassian.net/browse/EOSF-14
- Build a sample page where users can view and update profile information
Requires https://github.com/CenterForOpenScience/ember-osf/pull/27 to be merged
- `/profile/`

Add profile view/update route [EOSF-14]

---

tests/integration/components/file-renderer/component-test.js

Adds tests for https://openscience.atlassian.net/browse/EOSF-19
Adds component tests for file-renderer.

Add tests for the file-renderer component [EOSF-19]

---

tests/unit/controllers/file-test.js
tests/unit/controllers/node-test.js

https://openscience.atlassian.net/browse/EOSF-63
Adds controller unit tests for testing actions for adding and removing tags on nodes and files.  Integration test for component already exists.

Feature/Tags Widget Unit Tests [EOSF-63]

---

addon/components/tags-widget/component.js
addon/mixins/taggable-mixin.js

https://openscience.atlassian.net/browse/EOSF-73
Intern request. Clears form after tag added.  Based off of patterns in @abought's commenting widget https://github.com/CenterForOpenScience/ember-osf/pull/61.

feature/Clear form after tag added [EOSF-73]

---

addon/components/osf-navbar/component.js
addon/components/osf-navbar/template.hbs
addon/components/search-dropdown/component.js
addon/components/search-dropdown/style.scss
addon/components/search-dropdown/template.hbs
addon/styles/ember-osf.scss

https://openscience.atlassian.net/browse/EOSF-26
Adds search to navbar.  Gets rid of unnecessary imports.

Feature/Add Search to Navbar [EOSF-26]

---

addon/mixins/node-actions.js
addon/mixins/registration-actions.js
addon/mixins/taggable-mixin.js
tests/dummy/app/controllers/collections/index.js
tests/dummy/app/controllers/nodes/detail/draft-registrations/detail.js
tests/dummy/app/controllers/nodes/detail/draft-registrations/index.js
tests/dummy/app/controllers/nodes/index.js
tests/dummy/app/routes/collections/detail.js
tests/dummy/app/routes/profile.js

https://openscience.atlassian.net/browse/EOSF-89
Adds docstrings to the registration-actions/node actions mixins and taggable-mixin.  Adds docstrings to dummy app controllers/route actions for drafts, controllers, profile.

Feature/Some Mixin Docstrings [EOSF-89]

---

addon/adapters/osf-adapter.js
addon/mixins/node-actions.js
addon/models/contributor.js
addon/models/node.js
addon/models/osf-model.js
addon/serializers/contributor.js
package.json
tests/dummy/app/styles/app.scss
tests/dummy/app/templates/nodes/detail/index.hbs
tests/factories/institution.js
tests/factories/node.js
tests/unit/adapters/osf-adapter-test.js

https://openscience.atlassian.net/browse/EOSF-78
The OsfAdapter does quite a bit of heavy lifting that bypasses some Ember internals. We need unit tests to document and prevent regressions in this code.
Should mostly be added tests. Some bugs might get fixed in the process.

Add unit tests for OsfAdapter

---

addon/components/eosf-project-nav/component.js
addon/const/permissions.js
addon/models/user.js

https://openscience.atlassian.net/browse/EOSF-117
Model fields and changes required to support contribs modal dialog
Will add fields as needed throughout work on this PR.
Companion to https://github.com/pattisdr/osf.io/pull/5
None.

Model fields and changes required to support contribs modal dialog

---

addon/components/osf-navbar/component.js
addon/components/osf-navbar/template.hbs

Add hideSearch component param to osf-navbar

---

addon/components/dropzone-widget/component.js

Be able to pass defaultMessage to dropzone widget to override default  "Drop files here to upload"

Feature/ Add defaultMessage option to drop zone.

---

addon/components/osf-footer/component.js
addon/components/osf-footer/template.hbs

https://trello.com/c/K0uz5PEg/5-footers-don-t-match
Update footer links / code.

Update footer component to match OSF changes

---

addon/components/dropzone-widget/component.js
addon/mixins/cas-authenticated-route.js
addon/utils/auth.js
tests/integration/components/file-renderer/component-test.js

https://trello.com/c/9NfClWcQ/130-get-tests-passing-for-ember-preprints
Make CI relevant again: fix style and test failures

Fix CI and style failures

---

README.md

Fix malformed link in README file

---

addon/models/file.js

Needed for https://openscience.atlassian.net/browse/PREP-144
The version of the primary file for the preprint needs to be exposed in the view preprint page.
Adds currentVersion to the file model.

Feature/Add currentVersion to file model. [PREP-144]

---

.travis.yml
addon/components/navbar-auth-dropdown/component.js
addon/components/navbar-auth-dropdown/style.scss
addon/components/navbar-auth-dropdown/template.hbs
addon/components/osf-navbar/component.js
addon/components/osf-navbar/style.scss
addon/components/osf-navbar/template.hbs
addon/models/preprint-provider.js
addon/styles/addon.scss
app/components/navbar-auth-dropdown/component.js
package.json
tests/integration/components/navbar-auth-dropdown/component-test.js
tests/unit/models/preprint-provider-test.js

Needed for ember-preprints branded navbar.
Should be no visible functional changes on the osf-navbar

Moving out Navbar Auth Dropdown into its own component [PREP-217]

---

addon/components/license-picker/template.hbs

Purpose
--------
Match styles with the changes from https://github.com/CenterForOpenScience/ember-preprints/pull/214
Changes
---------
Remove unused class and replace with inline style definitions

add pre-wrap style to text [PREP-272]

---

addon/models/preprint.js

Feature/Fix typo in Preprints Model

---

addon/components/osf-navbar/template.hbs
addon/utils/ajax-helpers.js

https://openscience.atlassian.net/browse/EOSF-441
Navbar registries button now actually says Registries and points to the ember app.

[EOSF-441] Update navbar to have correct registries information

---

.dockerignore
Dockerfile

https://openscience.atlassian.net/browse/EOSF-498
* Local development with consuming apps
* Needed by CenterForOpenScience/osf.io#6952
N/A

[EOSF-498] Dockerize

---

addon/models/preprint-provider.js

N/A
Merge hotfix into develop.

Add domainRedirectEnabled to preprint-provider model

---

package.json

https://openscience.atlassian.net/browse/EOSF-
Add rebuild node-sass to scripts from @binoculars.

Feature/Rebuild node-sass

---

config/backends.json

https://openscience.atlassian.net/browse/EOSF-692
Fixes broken search page on staging 2/3 and test
Update to configuration
Search should work all environments
Check Preprints search to make sure that it's working again

[EOSF-692] Add SHARE urls for stage2, stage3, and test

---

addon/models/preprint-provider.js

https://openscience.atlassian.net/browse/EOSF-575
Add new preprint provider properties to model
Added footerLinks, allowSubmissions, and additionalProviders properties to preprint-provider model

Add new preprint provider properties to model

---

addon/components/navbar-auth-dropdown/template.hbs

https://openscience.atlassian.net/browse/EOSF-700
Fix the capitalization of the navbar in preprints.
Change "Sign in" to "Sign In"
None

Fix the capitalization of sign in in preprints navbar [EOSF-700]

---

addon/components/discover-page/component.js

https://openscience.atlassian.net/browse/EOSF-753
Update SHARE subject filter to work with custom taxonomies.
Changed from terms filter to multiple should match filters.
This only makes subject filters work when clicking on preprint tags on search results.

Update SHARE filter for custom taxonomies [EOSF-753]

---

addon/models/preprint-provider.js

https://openscience.atlassian.net/browse/EOSF-691
Add relationship from Preprint Provider to Highlighted Taxonomies
Added highlightedTaxonomies relationship to preprint-provider model
N/A

[EOSF-691] Added highlighted taxonomies relationship to preprint-provider model

---

addon/models/taxonomy.js

https://openscience.atlassian.net/browse/EOSF-691
Add the path attribute to the taxonomy model
Added path attribute to taxonomy model
N/A

[EOSF-691] Added path attribute to taxonomy model

---

addon/components/donate-banner/component.js
tests/integration/components/donate-banner/component-test.js

The current dates for the donate banner start at `8`.  The real dates should start at `7`.
Change the dates to start in August and end in September.

[EOSF-778] Fix donate banner dates

---

addon/components/new-osf-navbar/template.hbs
addon/helpers/build-secondary-nav-links.js
addon/instance-initializers/ember-osf.js
tests/unit/helpers/build-secondary-nav-links-test.js

https://openscience.atlassian.net/browse/EOSF-

Account for provider not being available right away

---

index.js

https://openscience.atlassian.net/browse/EOSF-794

Locate scss file properly

---

addon/components/new-navbar-auth-dropdown/component.js
addon/components/new-navbar-auth-dropdown/template.hbs
addon/components/new-osf-navbar/component.js
addon/components/new-osf-navbar/template.hbs

https://openscience.atlassian.net/browse/EOSF-758
To add analytics tracking to the new EmberOSF navbar.
Included Analytics Mixin on both navbar templates (main and dropdown)
Please check with the OSF part of this fix to make sure that both sides have tracking on the same items.

[EOSF-758] Add analytics to navbar

---

addon/components/new-navbar-auth-dropdown/template.hbs

https://openscience.atlassian.net/browse/EOSF-834
Make Logout link functional
Made logout action a "regular" action
Make sure Logout link works

[EOSF-834] Made logout action a regular action

---

addon/instance-initializers/ember-osf.js

N/A
Clone data object so it can be extended.
If data is defined, clone it before extending it with preprint words.
Make sure preprint words still works.

Clone data in tHelper reopen for preprint words

---

.bowerrc

N/A
Start using the new Bower registry.
Add registry entry to .bowerrc with the location of the new Bower registry.
N/A

Add registry entry to .bowerrc with new registry

---

CHANGELOG.md
addon/models/file.js

https://openscience.atlassian.net/browse/EOSF-770
Add more file operations to file model for use when editing.
Add `getContents()` and `updateContents()` methods to file model.
Make sure file contents are retrieved and updated properly.

[EOSF-770] More file operations in model

---

addon/mixins/cas-authenticated-route.js

https://openscience.atlassian.net/browse/EOSF-863
Using Firefox on staging and prod, if going to a page that has `cas-authenticated-route` mixin (before going to any other page of that ember app), the `beforeModel` hook would find the session to not be authenticated (the ember app still doesnt have an authenticated session) as the request to api would not resolve in time, and transition to CAS, which (since the user is authenticated) transitions back to the page, where the problem would reoccur infinitely. 
The mixin now attempts to authenticate if it finds the session to not be authenticated, prior to assuming that there is no auth and rerouting to cas
Going to `osf.io/preprints/submit` and logging in, or going to osf.io and logging in then going to `osf.io/preprints/submit` WITHOUT …

[EOSF-863] If auth route is not authenticated, attempt to authenticate before sending to CAS

---

addon/mixins/cas-authenticated-route.js

https://openscience.atlassian.net/browse/EOSF-863
Using Firefox on staging and prod, if going to a page that has `cas-authenticated-route` mixin (before going to any other page of that ember app), the `beforeModel` hook would find the session to not be authenticated (the ember app still doesnt have an authenticated session) as the request to api would not resolve in time, and transition to CAS, which (since the user is authenticated) transitions back to the page, where the problem would reoccur infinitely. 
The mixin now attempts to authenticate if it finds the session to not be authenticated, prior to assuming that there is no auth and rerouting to cas
Going to `osf.io/preprints/submit` and logging in, or going to osf.io and logging in then going to `osf.io/preprints/submit` WITHOUT …

[EOSF-863] If an auth route is not authenticated, first attempt to authenticate

---

CHANGELOG.md
addon/components/file-browser/component.js
addon/components/file-browser/template.hbs

To move the buttons and change styling to match file edit buttons on the OSF.
Change order and styling of buttons for consistency.
https://openscience.atlassian.net/browse/EOSF-927

[EOSF-927] Move buttons and change styling

---

addon/components/lazy-options/template.hbs

Make it look better.
Remove the 'Load More' text.
None
https://openscience.atlassian.net/browse/IN-77

[IN-77][EOSF] Lazyloading quick fix.

---

CHANGELOG.md
addon/locales/en/translations.js

Add works to preprint word translations
Add work to `en` locales translations file
N/A
[IN-105](https://openscience.atlassian.net/browse/IN-105)

[IN-105][Ember-OSF] Add works to preprint word translations

---

addon/locales/en/translations.js

Add `placeholderMessage`.
https://openscience.atlassian.net/browse/IN-163

[IN-163][Emberosf] Quickfix

---

addon/locales/en/translations.js

Fix navbar capitalization.
Fix navbar capitalization for navbar.
Now
Before
https://openscience.atlassian.net/browse/IN-163

[IN-163][Emberosf] Fix navar capitalization

---

addon/components/scheduled-banner/template.hbs

Fix banners when no link is provided
Update scheduled banner template 
Make sure banner displays both when link is provided or not.
[IN-159](https://openscience.atlassian.net/browse/IN-159)

[IN-159][EmberOSF] Fix banners when no link is provided

---

addon/metrics-adapters/keen.js

We need to anonymize the client IP address when storing data on keen.io for GDPR.
* Added `remove_ip_property: true`
Shouldn't need QA although would be good for someone to verify that the IP address is getting removed.
https://openscience.atlassian.net/browse/IN-369
Should go out with 0.9.0 registries and 0.120.0 preprints.

[IN-369][Ember-OSF] Anonymize the client IP address for keen adapter

---

CHANGELOG.md
addon/components/license-picker/template.hbs

Fix license FAQ link 
- Update the license picker template to use updated link.
Please make sure the license FAQ link points to http://help.osf.io/m/preprints/l/726873-preprint-faqs#how_should_i_license_my_preprint
[IN-362](https://openscience.atlassian.net/browse/IN-362)
N/A

[IN-362][EmberOSF] Fix license FAQ link 

---

CHANGELOG.md
addon/components/new-osf-navbar/component.js
addon/components/new-osf-navbar/template.hbs
addon/const/service-links.js
index.js

Waffles are broke for logged out users. The institution navbar item should be viewable for all but logged out users can't see it
Remove the waffle flag for the institutional navbar item. It should show up for everyone now (preprints and registries)
Make sure the institutions section shows up for logged in and logged out users on preprints and registries (preprints first, registries will be checked as a "hotfix" when 0.121.0 is through QA). 
https://openscience.atlassian.net/browse/IN-376
Did I get everywhere that needs to be changed? Here is the original PR: https://github.com/CenterForOpenScience/ember-osf/pull/385/

[IN-376][EmberOSF] Remove waffle for institution navbar

---

CHANGELOG.md
addon/components/discover-page/template.hbs

I'm a dirty rotten liar and forgot that carousels exist in ember-osf. 
Move the param to emberosf where the jumping around issue won't be noticeable.
Check both carousels again to make sure they look good and clicking items works as intended.
https://openscience.atlassian.net/browse/IN-386

[IN-386][EmberOSF] Fix discover page carousel

---

CHANGELOG.md

Updated changelog with divorce changes.
https://openscience.atlassian.net/browse/IN-98

Feature/NPD Ember-osf Changelog [IN-98]

---

addon/adapters/user-email.js
addon/models/user-email.js
addon/models/user.js
addon/serializers/user-email.js
app/adapters/user-email.js
app/models/user-email.js
app/serializers/user-email.js
package.json
tests/unit/adapters/osf-adapter-test.js
tests/unit/models/user-test.js
yarn.lock

Enable the ember app to get user's emails.
Adding a `user-email` model to get the user's email.
Adding a `emails` relationship on `user` model.
https://openscience.atlassian.net/browse/EMB-519

[EMB-519][EOSF] Add user-email model.

---

addon/components/validated-input/template.hbs

Pass html attributes to Textarea component.
https://openscience.atlassian.net/browse/ENG-559

[ENG-559] Pass html attributes to textarea

---

addon/models/preprint-request-action.js

preprint-request-action comments are user-input and can contain special characters. This makes sure they are decoded.
use fixstring transform for preprint-request-action comment
Will be tested in preprints.
https://openscience.atlassian.net/browse/ENG-743
n/a

[ENG-743] use fixstring transform for preprint-request-action comment

---

addon/models/file-version.js

Add `name` to file-version model.

[ENG-37] Add name field to file-version model

---

addon/components/osf-footer/template.hbs

The `Donate` link goes to the wrong place
One line change to update donate link
NA
https://openscience.atlassian.net/browse/ENG-1757
Just this one lineeee

[ENG-1757] Update donate link

---

Dockerfile
README.md

- Remove bower from documentation
- Remove bower install steps from README and bower steps in Dockerfile
NA
No ticket

Remove bower from documentation

---

addon/adapters/citation-style.js
addon/components/citation-widget/component.js
addon/components/citation-widget/template.hbs
addon/models/citation-style.js
addon/models/preprint-provider.js
addon/serializers/citation-style.js
app/adapters/citation-style.js
app/models/citation-style.js
app/serializers/citation-style.js
test-support/factories/citation-style.js
test-support/factories/preprint-provider.js
tests/unit/models/citation-style-test.js
tests/unit/serializers/preprint-provider-test.js

* Add citation-style model
* Update citation-widget to check for provider-specific citations
* Tests
* Update inSloanStudy boolean flag on preprint-provider
* Remove comment; Add assertionsEnabled to preprint-provider factory
* Add margin to non-0th citation-styles
https://openscience.atlassian.net/browse/IN-

[ENG-4567] Provider custom citation (#467)
