.ember-cli, .github/CONTRIBUTING.md, addon/adapters/node.js, addon/mixins/osf-login-route.js, app/locales/en-us/config.js, app/locales/en-us/translations.js, index.js, tests/unit/adapters/node-test.js
=> Some misc updates

addon/serializers/osf-serializer.js
None
Fix `keyForAttribute`, which was incorrectly camelCasing the API payload -- h/t @abought 
Fixing serialization/deserialization revealed an issue on the Node model where ember sends null values for optional fields (e.g. `templatedFrom`) instead of omitting them from the payload.
None
=> Fix osf serializer

addon/serializers/osf-serializer.js
none (sorry)
Possibly fix an error where models failed to save, because they were trying to save invalid values to the server. Also incorporates #27.
In certain cases, DRF will exclude fields (like `template_from`) from the payload if they are undefined. When ember serializes the fields in the model, it may include a value of `undefined` for that empty field, which leads to a 400 error (eg null value not allowed for field)
This candidate fix simply refuses to serialize an attribute if the value is undefined.
https://github.com/emberjs/data/blob/v2.5.1/addon/serializers/json-api.js#L410
This is an experimental fix, but has not been thoroughly tested. Use at your own risk. It appears to work for null and false values, as well as truthy.
The right way to confirm this would probably be to …
=> Fix serialization errors (not thoroughly tested)

addon/adapters/contributor.js, addon/models/contributor.js, addon/serializers/contributor.js, package.json, tests/dummy/app/controllers/nodes/detail.js, tests/dummy/app/helpers/bibliographic-helper.js, tests/dummy/app/helpers/permission-helper.js, tests/dummy/app/routes/nodes/detail.js, tests/dummy/app/templates/nodes/detail.hbs, tests/unit/helpers/bibliographic-helper-test.js
https://openscience.atlassian.net/browse/EOSF-38
Bulk update functionality https://openscience.atlassian.net/browse/EOSF-42 will improve this feature.  Right now, you can update multiple contributors in the dummy app, but it is making single, consecutive requests in the background to update each contributor.  There's no guarantee currently that these requests happen in the correct order.     This can cause problems, if for example, there are two contributors on the project, and I am the only admin. if I attempt to make you the admin, and change my permissions to read, this has to happen in the correct order.  You need to be an admin before I can remove myself as admin.
If bulk update functionality isn't eventually implemented, there could be additional checks to ensure the requests happen …
=> [Ready] Feature/node contrib management [EOSF-38]

addon/components/tags-widget/component.js, addon/components/tags-widget/template.hbs, addon/mixins/taggable-mixin.js, addon/models/file.js, app/components/tags-widget/component.js, tests/dummy/app/controllers/nodes/detail/files/provider/file.js, tests/dummy/app/controllers/nodes/detail/index.js, tests/dummy/app/templates/nodes/detail/files/provider/file.hbs, tests/dummy/app/templates/nodes/detail/index.hbs, tests/integration/components/tags-widget/component-test.js, tests/unit/mixins/taggable-mixin-test.js
https://openscience.atlassian.net/browse/EOSF-59
Adds tags component and demonstrates use for both node tags and file tags in the dummy app.
addATag and removeATag methods on the controllers are a little weird.  I was having a hard time getting `snapshot.record.changedAttributes` to update.  For adding a tag, the only way I could get it to change was if I made a copy of the current tags (that did not reference the original), pushed the new tag onto the list, and then set the tags to this list.  If I pushed the new tag onto the current tags and then tried to set, changedAttributes would be an empty object.
Also, adding/removing tags from files are currently creating an extra log (checked_in), which is an OSF problem, to be fixed here …
=> Feature/Tags Widget [EOSF-59]

addon/serializers/osf-serializer.js
https://openscience.atlassian.net/browse/EOSF-64
❗ blocked by https://github.com/CenterForOpenScience/osf.io/pull/5823
Previously in the APIv2, embedded resources would be directly embedded rather than returning a relationship link.  Which works fine until you need the link!
So for collections in the dummy app, we needed to embed linked_nodes so we could see the projects in the collection.  But when we went to add a project to the collection, we didn't have the link to do so.
Uses the new links returned by https://github.com/CenterForOpenScience/osf.io/pull/5823 to send the request instead of generating our own.  Merges any links returned with the embedded resource with the links under relationships so all links are preserved.
=> Feature/Preserve New Relationship Links in Embeds [EOSF-64]

addon/models/node.js, addon/serializers/osf-serializer.js
https://openscience.atlassian.net/browse/EOSF-61
The default for our PATCH requests right now is to serialize the entire object and send it. Instead, we should just serialize the few fields we want to change.  This is important for when multiple users are trying to update things simultaneously, where your changes could overwrite my changes.
Also brings node links functionality up to date with latest relationship changes.
Method was just to call super, and let all attributes be serialized and then remove the fields not present in changedAttributes().
None
=> Feature/PATCH Requests Should Serialize only Dirty Attributes [EOSF-61]

addon/mixins/paginated-route.js, addon/models/collection.js, addon/models/comment-report.js, addon/models/comment.js, addon/models/contributor.js, addon/models/file-provider.js, addon/models/file-version.js, addon/models/file.js, addon/models/institution.js, addon/models/log.js, addon/models/node-link.js, addon/models/node.js, addon/models/registration.js, addon/models/user.js
https://openscience.atlassian.net/browse/EOSF-71
Help implementers discover how to use models.
In source code, provide a link to APIv2 browseable docs, as the source of record for field definitions and usage. Because relationship fields are complicated, I've tried to map this to as many relevant routes as I can find based on APIv2 serializers.
Additionally, improve documentation and URL param configuration for the pagination mixin to match recently merged changes.
BrianG has indicated that the API team is investigating how to make these links clickable. Currently, clicking these links takes you to swagger docs but does not expand the relevant section.
They have recommended [swagger docs](https://api.osf.io/v2/docs/) as entry point going forward.
None.
=> Add doc links to model source code

README.md, blueprints/ember-osf/files/config/_local.yml
None.
Add REDIRECT_URI param to blueprint to reflect recent refactorings. ([ref](https://github.com/CenterForOpenScience/ember-osf/pull/83#discussion_r68399798))
Also add documentation as appropriate.
Need to confirm that the specified default values are correct for local development scenarios.
If blueprint changes are propagated to a user's `config/local.yml` file, this should fix a bug where the `/login` functionality fails due to `redirect_uri=undefined` in the CAS URL.
=> Add REDIRECT_URI param to blueprint

.gitignore, addon/mixins/infinity-custom.js, package.json, requirements.txt, yuidoc.json
https://openscience.atlassian.net/browse/EOSF-81
Demonstrate ability to dynamically generate documentation for ember-osf modules.
This is the same doc generator and convention as used by ember. Most of our docstrings already follow these conventions.
A separate PR would be required if we wanted to serve this via github pages. (with autodeployment code in this branch)
See sample deployment here: http://abought.github.io/ember-osf/
Install YUIDoc, then run it without arguments from the `ember-osf` root folder. Docs will be deposited in the `docs/` folder, as specified in yuidoc.json.
`npm -g install yuidocjs`
`yuidoc`
Styling and improved text can move to a future ticket: get tooling out there and let the whole team make improvements.
Here is ember's yuidoc.json file for comparison: …
=> Set up YUIDoc to work with ember-osf

package.json
None.
A new consuming app failed to build. Moving `toastr` from `dependencies` to `devDependencies` fixed this issue.
Ours is not to question why....
Well, actually, that's the opposite of true. We're not sure why this works. Exercise your own judgment if this turns out to be problematic.
None. Toast is used on the nodes detail page (edit node settings toggle panel), if you want an example to confirm it still works for the dummy app.
=> Fix toastr build error in consuming apps

addon/serializers/comment.js
See: https://openscience.atlassian.net/browse/OSF-6646
Comment serialization for the replies relationship is incorrect, which confuses ember-data (which uses data/relationships/<name>/links/related to determine if a related field has data) This PR temporarily patches the serialization client side until we can fix the API.
=> Add temporary fix for Comment.replies serialization

addon/components/dropzone-widget/component.js
None.
Improve `dropzone-widget` ease of use by exposing event bindings to the component itself, rather than using a listeners object. This allows directly passing actions in to the component (e.g. `success`, `addedfile`).
Also, prevent dropzone from rebinding `this` to itself in event listeners. This allows listeners (typically Ember components or controllers) to retain their context.
- Perhaps passing the component and the dropzone object to each listener is unnecessary
- Dropzone allows binding multiple listeners to an event, so `addedfile` will not be overwritten
None, this is a component.
=> Flatten dropzone-widget events

addon/services/file-manager.js, tests/unit/services/file-manager-test.js
https://openscience.atlassian.net/browse/EOSF-113
- When `file-manager` fails to fetch a new file's info, throw an error to reject the promise instead of just returning `undefined`
- Fix the bug that revealed the reported bug: Query for the new file by name, instead of looking at just the first page of files returned by `reload()`. If the upload succeeds, fetching metadata should always succeed as well.
=> [fix] Fetch new file info more appropriately

package.json
None
This fixes an issue that broke addon-consuming apps that used ember 2.7. (ember internals were reorganized. See ember-i18n/issues/385
No side effects. We may get some template lint warnings with new ember versions, telling us that we haven't translated text. We'll ignore those for now.
None. Dummy app still appears to work.
=> Bump i18n dependency version

addon/authenticators/osf-cookie.js, addon/components/oauth-popup/template.hbs, addon/components/osf-navbar/template.hbs, addon/mixins/osf-cookie-login-route.js
https://openscience.atlassian.net/browse/PREP-87
Fix issue where (using cookie auth) the index page failed to load because the user was logged out.
When user was not logged in, beforeModel hook returned a rejected promise and failed. Catch that error and do nothing, so hook can pass through. (this just gets credentials if possible; it doesn't impose a hard requirement that the user be logged in)
BeforeModel hook (and ember simple auth) expect an ember promise, but receives a jquery object with slightly different semantics. Massage the promise type so things work correctly.
Anything using cookie auth: application route, eg in osf-ember and preprints app.
=> Fix error where cookie auth beforeModel hook failed

addon/mixins/commentable.js, addon/mixins/node-actions.js
https://openscience.atlassian.net/browse/EOSF-139
Although we save relationships through the parent model, actions that create something should return the newly created object, not just the thing used to handle the save.
Checked the following applications for usages of these actions; this seems compatible, but let me know if breakages are discovered.
- `ember-osf` dummy
- osf.io `feature/osf-ember` branch (and PRs)
- `ember-share`
- `ember-preprints`
- `osf-meetings`
Anything that depends on the node actions mixin to:
- create a child node (`addChild`)
- create a node link (`addNodeLink`)
- add node contributors (`addContributor`)
- add comments (`addComment`)
Also changes the `Commentable` mixin similarly. Cross-reference with standing PR: …
=> NodeActions that create something should return the new object

addon/components/dropzone-widget/component.js
https://openscience.atlassian.net/browse/PREP-112
Support changes required by the ember-osf "add/edit" page.
- Support cookie auth in dropzone widget
None.
=> [rfr] Changes to support preprints add/edit page

addon/adapters/contributor.js, addon/mixins/node-actions.js, addon/models/contributor.js, addon/models/node.js, addon/serializers/contributor.js
Accommodates API changes to how unregistered contributors are created, https://github.com/CenterForOpenScience/osf.io/pull/6157.
Fixes PATCH contributors, (updating permissions/bibliographic, reordering contribs were not working because user id instead of contrib id in response).
=> Feature/Handling API Unregistered Contributor changes

addon/components/tags-widget/component.js, addon/mixins/taggable-mixin.js, tests/dummy/app/templates/nodes/detail/files/provider/file.hbs, tests/dummy/app/templates/nodes/detail/index.hbs, tests/integration/components/tags-widget/component-test.js, tests/unit/controllers/file-test.js, tests/unit/controllers/node-test.js
https://openscience.atlassian.net/browse/PREP-55
❗ This PR is a dependency for https://github.com/CenterForOpenScience/ember-preprints/pull/46
⚠️ This is a backwards-incompatible change. It changes the call signature of actions on the TaggableMixin.
Supports tagging on pages where the thing to tag is not defined in the `model` hook of the route.
Changes how the `addATag` and `removeATag` mixins are used. Instead of passing `addATag=(action 'addATag')`, curry it so that the first argument is always implicitly there for any components (like `tags-widget`) that need it:
`addATag=(action 'addATag' model)`
This makes the mixin less tied to how variables are named on the route. (widgets only have to decide to do with tag text, not figure out what model to use)
This will break any consuming apps …
=> [api-change] Improve taggable mixin by removing hard-coded path to taggable resource

addon/components/file-browser/template.hbs, addon/models/node.js
- Removes "File" header from file-browser component. User should be able to determine their own label.
- Remove index from addContributor action.  More work will be needed ember side to support index on create.
=> Feature/Remove File Header from File Browser Component

addon/components/osf-navbar/style.scss, addon/components/osf-navbar/template.hbs
Add option to navigation bar to show link to Service if a service exists; such as Preprints
Initial implementation to work with Preprints. May need further considerations down the line. 
Should not affect the cases where no service is provided 
None
=> Add service option to navbar template

addon/authenticators/osf-token.js, addon/components/osf-navbar/component.js, addon/components/osf-navbar/template.hbs, addon/mixins/cas-authenticated-route.js, addon/mixins/osf-agnostic-auth-controller.js, addon/mixins/osf-agnostic-auth-route.js, addon/mixins/osf-cookie-login-controller.js, addon/mixins/osf-cookie-login-route.js, addon/mixins/osf-token-login-route.js, addon/utils/auth.js, index.js, tests/dummy/app/templates/application.hbs, tests/integration/components/osf-navbar/component-test.js, tests/unit/mixins/cas-authenticated-route-test.js, tests/unit/mixins/osf-agnostic-auth-controller-test.js, tests/unit/mixins/osf-agnostic-auth-route-test.js
https://openscience.atlassian.net/browse/PREP-118
Companion ember-preprints PR to follow.
Allow a single application to support both cookie and token based auth. Sample use case is to run preprints from within the OSF, as well as branded on different domains.
Imports are evaluated before code, so a new `OsfAgnosticAuth*` set of mixins was needed to support making auth configurable based on the value of `authorizationType` in `config/environment.js`.
For now, the token auth login button forces the user to go wherever the app registered to be the REDIRECT_URI (eg, the homepage). We may want more fine-grained redirects in the future (return the user to the page they were on when they clicked the login button)
I did experiment with REDIRECT_URIs that contained additional query params, but in …
=> Allow same application to support cookie and token auth

addon/adapters/contributor.js, addon/mixins/node-actions.js, addon/models/contributor.js, addon/models/node.js, tests/dummy/app/components/contrib-manager/component.js
Vaguely related to Preprints Ticket - https://openscience.atlassian.net/browse/PREP-130
Preprints needed the ability to send an email to preprint authors after the whole preprint process has been completed, which does not happen until after a normal project has been created and contributors added to it. So, we needed a way to pass along OSF API v2's query parameter `send_email=False` when creating a contributor from Ember OSF through the preprints interface! 
Then, the email can be sent after the whole preprint process is completed, and users unfamiliar with the OSF can receive an email with language about the preprint and not an unanticipated "project."
- I am very new to ember, so style, testing, really any improvement pointers welcome!
- I also may very well have broken other places …
=> Add the ability to pass along sendEmail=False when adding a contributor

addon/components/osf-navbar/component.js, addon/components/osf-navbar/template.hbs
Let users customize url used for navbar signup button.
(default url is still the normal OSF register page)
=> Use custom OSF signup page URL

addon/authenticators/osf-cookie.js
Fix an issue with cookie auth, where clicking logout button in the OSF navbar reloaded the page, but did not invalidate the session.
This fix is kind of a hack. It seems to be a race condition. The code hits the `window.location` branch of the if statement, then goes to the next line with a resolved promise- and upon resolution, the navbar logout action happens to call `window.location.reload`.
This fix tells simple-auth to stop the normal invalidation process if redirecting (so that the redirect is actually the last line of code to be run, and it does not move on and obey a reload instead)
At last check this reload was the easiest way to ensure state was cleaned up for both token and cookie auth- clean reset of the page. In any event, since this seems to be a race condition, the …
=> Hacky fix for logout race condition

addon/components/file-renderer/template.hbs
https://trello.com/c/Rv8Flwut/144-txt-file-on-preprint-not-rendering-properly
Text files are getting cut off. Quick fix is to add scrolling to file renderer. Next steps will add dynamically resizing height based on height of content.
=> Feature/Add Scrolling to File Renderer

addon/components/file-renderer/component.js, addon/components/file-renderer/template.hbs
https://openscience.atlassian.net/browse/PREP-147
It looks like the mfr options do not include allowing full screen as default. This is useful for preprints and I think it would be a good default to have. 
I don't know if the optionality of this needs to be worked out more. I did add it as a variable and did not hard code it in but it's the default. 
NA
=> Add allowfullscreen as default in file-renderer [PREP-147]

addon/adapters/user.js, addon/models/osf-model.js, addon/serializers/osf-serializer.js, addon/utils/load-relationship.js
Needed for https://github.com/CenterForOpenScience/ember-preprints/pull/141
Selecting existing project for preprints - need to get format to resemble dashboard format.  For example,  Project / ... / Private / Component, instead of Component".  
Changes
=> [Ready to Review] Feature/Embed Root and Parent on User Nodes

README.md
Discourage leaking of sensitive info, and make clear that tokens are only used locally.
The fact this addon uses a token at all is simply a convenience for people using FakeCAS in local development; tokens are ignored when communicating with remote servers (like staging or production)
=> Clarify README: tokens are sensitive info

addon/mixins/node-actions.js, addon/models/node.js
https://openscience.atlassian.net/browse/PREP-142
❗ Blocks https://github.com/CenterForOpenScience/ember-preprints/pull/176
Implements a rough version of bulk add.  Not all contributors are getting adding to component from parent project in staging2 preprints.  Concurrency issue suspected.
Uses AJAX request for bulk add, similar to how we are doing bulk update.  More work needed to get bulk functionality working properly with Ember.
=> Feature/Bulk Add Contributors [PREP-142]

addon/components/tags-widget/component.js
This is to fix the preprint submission form for pasting multiple tags in a comma-delimited list. 
The bug is detailed in PREP-155. It is not apparent until the Preprint is submitted.
To link the project for Preprints locally:
```bash
cd $PROJECT_DIR/ember-osf && npm link
cd $PROJECT_DIR/ember-preprints && npm link ember-osf
ember serve
```
it should now have the tags separated out when you submit a preprint after pasting a comma-delimited list of tags:
=> Separate tags in the model when pasted as a comma-delmited list [PREP-155]

package.json, requirements.txt
- Bump version to match release tags on master
- Remove usage of a python script that deployed docs to gh-pages; we now commit directly to `docs/` folder of master branch instead.
=> Bump version & remove legacy doc deployment process

addon/components/osf-copyright/template.hbs
https://openscience.atlassian.net/browse/PREP-244
See ticket
`Center for Open Science` now goes to https://cos.io instead of http://centerforopenscience.org
=> Update link for [PREP-244]

addon/authenticators/osf-cookie.js, addon/components/navbar-auth-dropdown/component.js, addon/utils/auth.js
https://openscience.atlassian.net/browse/PREP-253
Needed for branded preprints redirects
* redirect_url is appended to the logout page as a query param, if the value is set on the component. If not, it goes to the default logout page
* Add trailing slash after login for the login uri
N/A
CenterForOpenScience/ember-preprints#190
=> Add ability to have a redirect url after logout [PREP-253]

addon/components/license-picker/template.hbs
Make the style of the word required match the preprint form,
=> [EOSF-158] Make required on license widget match preprint form

addon/adapters/osf-adapter.js, addon/mixins/node-actions.js, addon/models/collection.js, addon/models/node.js, addon/serializers/linked-node.js, addon/serializers/osf-serializer.js, tests/dummy/app/routes/collections/detail.js, tests/dummy/app/templates/collections/detail.hbs, tests/dummy/app/templates/nodes/detail/index.hbs, tests/unit/models/collections-test.js, tests/unit/serializers/collection-test.js, tests/unit/serializers/node-link-test.js
https://openscience.atlassian.net/browse/PREP-246
❗️ Must be accompanied by https://github.com/CenterForOpenScience/osf.io/pull/6563
The latest version of the API will be 2.3 once the above PR is merged. In order for preprints to use this latest version of the API, ember-osf needs to be upgraded.  This affects things like pagination links, linked nodes, linked registrations, institution components, and merged users.
TODO
Are there other places that will be affected by this version change?  Breaking API changes are listed [here]( https://osf.io/y9jdt/wiki/Changelog/?view).  Version 2.3 (pending) will prevent merged users from being returned in `GET /v2/users/`.  
There needs to be a bigger discussion regarding how we are updating Ember-OSF.  Which groups are using ember-osf?  Will they be …
=> Feature/Upgrade to use APIv2.3 [PREP-246]

addon/components/license-picker/component.js
From the perspective of the component, copyrightHolders it should be only a string, never an array. This helps fix licenseChanged not always being accurate on preprints edit.
=> [PREP-278] CopyrightHolders should always return a string to the controller

addon/serializers/osf-serializer.js
Only ten results are loading for project dropdown on preprints.  This is caused by the Ember-OSF recent upgrade to APIv2.3 https://github.com/CenterForOpenScience/ember-osf/pull/153.  Meta information was previously under links, but newer versions of the API have meta as a top-level object.  Ember-osf > osf-serializer adds a field to meta which specifies how many pages are to be loaded. However, a shallow copy is used, so when calculating total pages to be loaded, the total number of results to be loaded is overridden.  Before, when meta was under links, this shallow copy was not a problem.
Deep copy payload information, so total number of results is not overridden by total number of pages.   
This is visible in preprints, where all valid projects should load on project dropdown.
=> [hotfix] Feature/Total Number of Results being Overridden

addon/components/license-picker/component.js, addon/components/license-picker/template.hbs
https://openscience.atlassian.net/browse/EOSF-159
Related to:
https://openscience.atlassian.net/browse/EOSF-397
Send PressSubmit action up from the license widget if enter is pressed on the input fields.
=> [EOSF-159] Allow enter to send action on license widget

addon/adapters/preprint.js
https://openscience.atlassian.net/browse/EOSF-160
Related to:
https://openscience.atlassian.net/browse/EOSF-187
Two requests are being sent to update preprint licenses, which sometimes results in extra logs.  The OSF Adapter overrides updateRecord to handle changed relationships and changed attributes separately.  Multiple requests will be sent for these items.  However, preprints PATCH requests from the API can have both relationships and attributes in the request - one request is meant to be sent to PATCH the preprint directly, not multiple requests to different resources.
One request sent to PATCH preprint instead of two. Since preprints PATCH requests seem to be more along the lines of what Ember expects, instead of overriding overrides in the Preprints Adapter to get it to work, …
=> Feature/Preprint Adapter Changes [EOSF-160]

README.md, index.js
https://openscience.atlassian.net/browse/EOSF-105
Ember-osf is designed to work with two types of authorization: cookies and tokens.
Previously, getting a new app to work required manually setting a secret config parameter, `authorizationType`.
This PR allows the addon to set a [default value](https://ember-cli.com/api/classes/Addon.html#method_config) to that consuming apps don't need more boilerplate to use OAuth 2.0. For internal COS products based on cookie auth, we add documentation of the configuration changes needed to get things working.
This PR is about the new developer experience- so the best way to test it is using a fresh ember app. You can probably test this by modifying the `ember-osf` dummy app [config file](https://github.com/abought/ember-osf/blob/5ccb027abe248e3d4fa7f8fc …
=> [rfr] Default authorizationType (and document secret config param) [#EOSF-105]

addon/models/preprint-provider.js
https://openscience.atlassian.net/browse/EOSF-497
On branded preprints, communities need a way to give 'About' information to users.
A new model field is needed to hold the link information.
=> Add new model field for the about link [EOSF-497]

addon/components/license-picker/template.hbs
https://openscience.atlassian.net/browse/EOSF-481
To fix in-line styling on the full license text widget.  Prevents the text from breaking mid-word if it needs to break to a new line.
None
None
=> [EOSF-481] Formatting on Full License Text Widget for Preprints

addon/models/file-version.js
https://openscience.atlassian.net/browse/EOSF-551
Needed for APIv1 parity and to be able to show previous version dates in preprints
❗️Needs:
* CenterForOpenScience/osf.io#6947
Needed by:
* CenterForOpenScience/ember-preprints#285
Minor change just to the model so that preprints can get the date created from file versions.
N/A
=> [EOSF-551] Add dateCreated to file version model

addon/components/osf-footer/template.hbs
https://openscience.atlassian.net/browse/EOSF-524
- The links for the Reproducibility Projects in the Ember footer lead to https://osf.io/preprints/ezcuj/wiki/home/ and https://osf.io/preprints/e81xl/wiki/home/, respectively, which just leads to "Page not found." The word "preprints" should not be in the url.
The same issue is occurring with the "FAQ/Guides" and "Explore" links as well.
- href for the mentioned links are updated to point to the site root.
=> Reproducibility Projects, FAQ/Explore links in footer redirect incorrectly [EOSF-524]

addon/serializers/comment.js
https://openscience.atlassian.net/browse/EOSF-95
Logic in the comment serializer is no longer needed (I actually think it was preventing it from working properly)
=> [EOSF-95] Remove unneeded comment serializer logic

addon/serializers/preprint-provider.js, app/serializers/preprint-provider.js, tests/unit/serializers/preprint-provider-test.js
N/A
Add missing preprint-provider serializer, which simply inherits osf-serializer.
Added preprint-provider serializer and auto-generated "it serializes" test.
Things using multi-word preprint-provider properties should work now.
=> Added missing preprint provider serializer

addon/components/search-dropdown/component.js
N/A
Make documentation better. This component doesn't work if you use it the way the sample suggests.
h/t @atelic
Does the same thing as PR #200, but fixes the original file rather than autogenerated artifact.
No user facing changes. Documentation should be slightly more useful.
=> Fix typo in docs for search-dropdown component 

addon/models/preprint-provider.js
https://openscience.atlassian.net/browse/EOSF-622
Brings Preprint Provider model in parity with OSF API Model
One-line change, addition to model
N/A
Relates to: CenterForOpenScience/osf.io#6793
=> [EOSF-622] Add domainRedirectEnabled to preprint-provider model

addon/components/discover-page/style.scss, addon/components/discover-page/template.hbs
https://openscience.atlassian.net/browse/EOSF-659
Fix inability to click x to remove active filter in Firefox
Made the fa-icon a button tag instead of the default i tag and changed containing tag to be a span.
Need to check in all browsers. Tested in Chrome, FF, and Safari on Mac.
Note: In Firefox the click event is attached to the button, even when the button contains another object. This differs from Chrome and Safari (unsure about IE). Try https://jsfiddle.net/5pvLez34/ in various browsers.
=> [EOSF-659] Make fa-icon a button rather than an i inside a button

addon/components/license-picker/component.js
https://openscience.atlassian.net/browse/EOSF-601
Reverse the debounce logic. Autosave makes sense to be calling a save action anytime any change happens, leaving the behavior of debouncing to be handled by whatever controller is consuming the component. In the use case in preprints, no debouncing is necessary. 
A lot of small improvements were removed for the purpose of reversing debonucing logic (which was causing a bunch of bugs). Maybe worth looking into this again in the future. Ticket tracking those improvements being reintroduced: https://openscience.atlassian.net/browse/EOSF-671
=> [EOSF-601] Reverse debouncing logic on license widget

bower.json
https://openscience.atlassian.net/browse/EOSF-511
Current ember-osf develop build was failing.  Cause was C3 and D3 package versions "~" - thanks @binoculars for figuring this out!
Pinned to specific C3 and D3 versions
=> Feature/C3 and D3 Package Versions [EOSF-511]

.travis.yml
https://openscience.atlassian.net/browse/EOSF-699
Use "sudo: required" in Travis to get a build environment with more memory
Changed to "sudo: required" in .travis.yml
=> [EOSF-699] Use sudo:required in Travis

.travis.yml, testem.json
N/A
Use headless Chrome for tests
Added chrome:stable addon for Travis and configure testem to use headless Chrome
=> Use headless chrome for tests

addon/components/navbar-auth-dropdown/component.js
https://openscience.atlassian.net/browse/EOSF-633
When one logs out when on a branded preprint service, they will stay on the lading page instead be redirected to the OSF logout page.
Corrected the query param from 'next_url' to 'next'.
None
=> Change query param from 'next_url' to 'next' for logout redirect [EOSF-633]

addon/components/discover-page/component.js, addon/components/discover-page/template.hbs, addon/components/search-facet-worktype/component.js, addon/components/search-facet-worktype/template.hbs, addon/components/search-result/component.js, tests/integration/components/search-facet-worktype/component-test.js
https://openscience.atlassian.net/browse/EOSF-680
❗️ is needed for https://github.com/CenterForOpenScience/ember-preprints/pull/383
Make changes to the discover-page widget that are needed for the ASU repository.
- Provider is passed into component
- Search-facet-worktype component is now taking care of building the list of types itself, instead of passing them into the component.  This allows preprints to be able to use this facet.
- Only show add preprint box on submissions page allowSubmissions is true.
- Conditionally modify search query.  If additionalProviders exist, pass all providers (like ASU, Symbiota, etc. into query). Otherwise, just pass single provider like engrxiv.
- Tags on search result are conditionally clickable (allowed if additionalProviders exist, because …
=> Feature/Discover Page Changes for ASU Repository [EOSF-680]

addon/components/search-result/component.js, addon/components/search-result/template.hbs
https://openscience.atlassian.net/browse/EOSF-625
On preprints search, the dates from SHARE are not being displayed properly.  
For example, on this preprint the date modified shows 2017-06-04:
But when you look at the date_updated in the elastic search results it shows 2017-06-05:
The issue is coming from the moment-format function used in the template.  After the fix, the date_updated shown in the search results match the elastic search results:
The main issue comes from the moment-format function trying to update the date being given to match the current time zone.  The primary change was to create a computed function that handles the format of the date instead of the old moment-format function.
(UTC) has also been added to the end of the timestamp label so that users know exactly what …
=> [EOSF-625] Fix date updated/modified on preprints search

addon/components/osf-footer/template.hbs
https://openscience.atlassian.net/browse/EOSF-669
Facebook and Google Plus Links were changed, needed the ember footer to reflect this.
Changed the hyperlinks for the Google Plus and Facebook icons.
None
=> Update Google Plus and Facebook footer links [EOSF-669]

addon/models/preprint-provider.js
https://openscience.atlassian.net/browse/EOSF-713
emailSupport was removed from the API and the ember model, but it is used by the 404 page for branded preprints.
Added emailSupport back to the preprint provider model.
Make sure email address and link appear for branded preprint 404 pages.
=> Add emailSupport back to the preprint provider model [EOSF-713]

addon/components/discover-page/component.js
https://openscience.atlassian.net/browse/EOSF-680
When building hyperlinks from returned SHARE search, "creative work" results were being returned, and the url is built from the type. Remove white space from type.
URL's being returned should look like: https://staging-share.osf.io/creativework/46107-45A-314
=> Feature/Remove White Space from SHARE Resource Type [EOSF-680]

addon/helpers/extract-doi.js, addon/utils/extract-doi-from-string.js, app/helpers/extract-doi.js, app/utils/extract-doi-from-string.js, tests/unit/helpers/extract-doi-test.js, tests/unit/utils/extract-doi-from-string-test.js
https://openscience.atlassian.net/browse/EOSF-631
Moved method for extracting a DOI from a string into a utility and wrapped it with a helper.
Added utils/extract-doi-from-string and helpers/extract-doi
Internally used utility. Should be tested in interfaces that parse DOIs from strings (e.g. preprint submission).
=> [EOSF-631] extract DOI utility and helper

config/backends.json
https://openscience.atlassian.net/browse/EOSF-682
Fix share links on preprint results entries.
Add trailing slash to production share url in config file.
This problem only shows up on production. There will be no changes on staging.
=> hotfix/Fix production's shareBaseURL: add trailing slash [EOSF-682]

addon/components/search-facet-worktype-button/style.scss, addon/components/search-facet-worktype-button/template.hbs
https://openscience.atlassian.net/browse/EOSF-733
Fix search facet worktype expand button in FF & Safari
Moved font awesome icon classes to button itself to avoid zero-width button in Firefox and Safari
Make sure this also works in IE.
=> [EOSF-733] Fix search facet worktype expand button in FF & Safari

addon/components/new-osf-navbar/template.hbs, addon/helpers/build-secondary-nav-links.js, addon/locales/en/translations.js
https://openscience.atlassian.net/browse/EOSF-541
Shorten "Add a preprint" to "Add" for small and xs screens"
Added template logic to display shortened version for small and xs screens.
Breakpoint is at 992px wide
=> [EOSF-541] Shorten "Add a preprint" to "Add" in navbar for small screens

addon/components/discover-page/template.hbs
https://openscience.atlassian.net/browse/EOSF-720
Remove “X many preprints have been archived” from  Paleorxiv.
Now for branded preprint providers shareTotal is set to zero and there is no longer a request to grab the number of share results.
Does Paleorxiv no longer show a “X many preprints have been archived.” Does it still show up on registries and the landing page.
=> Feature/remove shareTotal request for branded preprint providers [EOSF-720]

addon/mixins/cas-authenticated-route.js
https://openscience.atlassian.net/browse/EOSF-762
Fix next url for CAS when attempting to access a page that require authentication
Prepend next url with window location origin
Make sure redirecting through CAS works properly when clicking "Add a preprint" and not logged for:
* unbranded preprints
* branded preprints
* branded preprint domains
=> [EOSF-762] Prepend next url with window location origin

addon/components/discover-page/component.js, addon/components/discover-page/template.hbs
https://openscience.atlassian.net/browse/EOSF-694
Instant search is currently being implemented on the discover search page for Registries and Preprints.  This is clashing with the new Lucene search syntax that has recently been implemented.  The purpose of this ticket is to remove the instant search feature so that the user can fully type in their search criteria before getting back results.
The search bar is now directly calling the search action on enter keypress or when the search button is called.  The instant search function has been removed, so now the user has to fully enter their phrase before getting back any results.
Before the changes, if the user typed some Lucene syntax into the search bar it would return an error with notes on Lucene syntax:
Now that it waits for the user …
=> [EOSF-694] Discover search on 'enter' instead of onkeypress

addon/models/taxonomy.js
https://openscience.atlassian.net/browse/EOSF-753
Added shareTitle property to taxonomy model to use for querying SHARE.
Added shareTitle property to taxonomy model
Make sure shareTitle property is populated once the API includes it.
=> Added shareTitle property to taxonomy model [EOSF-753]

addon/components/discover-page/template.hbs, addon/components/search-result/component.js, addon/components/search-result/template.hbs, addon/helpers/custom-taxonomy-filter.js, app/helpers/custom-taxonomy-filter.js, tests/unit/helpers/custom-taxonomy-filter-test.js
https://openscience.atlassian.net/browse/EOSF-754
Subjects are now being passed back from SHARE as strings contained their hierarchy. We want to show to the user the same things we used to (deduplicated parents and children as separate 'tag'-like subjects), but retain the hierarchy and taxonomy tag (i.e. 'bepress'), so they can be filtered properly.
Add custom taxonomy helper so filters can be shown properly
Add logic to separate out and deduplicate all subjects in a search result, to be displayed as such but also filtering using their original value
=> [EOSF-754] Fix display of custom taxonomy subjects

addon/components/discover-page/component.js, addon/components/search-result/component.js
https://openscience.atlassian.net/browse/EOSF-786
When on the unbranded aggregate discover page, use subject_synonyms (if available) instead of subjects.
* Add subject_synonyms to results map
* Add logic to use subject_synonyms when appropriate
Make sure bepress subjects are used on unbranded aggregate discover page and custom taxonomy subjects are used on branded provider discover page. Make sure subject tags for preprints without custom taxonomies work properly.
=> [EOSF-786] Use subject_synonyms if available and on unbranded discover page

addon/components/new-osf-navbar/template.hbs, addon/components/osf-navbar/style.scss, addon/helpers/build-secondary-nav-links.js, addon/locales/en/translations.js
https://openscience.atlassian.net/browse/EOSF-772
To add a 'Donate' button to the ember side of the osf (preprints and registries).
Added the 'Donate' button to the navbar and added to some of the necessary files: 
- translate.js to make the 'Donate' word more standardized
- build-secondary-nav-links.js to add the 'Donate' button to the necessary arrays that are looped to determine what goes on the navbar
=> [EOSF-772] Add 'Donate' link to navbar

addon/instance-initializers/ember-osf.js, package.json
https://openscience.atlassian.net/browse/EOSF-655
Hotfix for ability to interpolate preprintWords in i18n.t method instead of just the t helper.
Override i18n.t method instead of t helper to inject preprintWords at a lower level.
Make sure everywhere that should say preprint(s) does (or alternate text for that provider). One example fixed with this PR is the "Add a preprint" link in the unbranded navbar.
=> [EOSF-655] Hotfix/0.8.2

addon/utils/fix-special-char.js, tests/fixtures/specialChars.js
https://openscience.atlassian.net/browse/EOSF-756
To escape < and > in preprint abstracts.
Added the < and > symbols to the characters being escaped in the `fix-special-char` helper.
The < and > symbols now show up right in both the abstract and in the tags.
=> [EOSF-756] Add < and > to special escaped characters

.nvmrc, .travis.yml, Dockerfile, package.json
❗️Needs CenterForOpenScience/osf.io#7350
https://openscience.atlassian.net/browse/EOSF-554
Updates Node.js version to 8
Remove lts/boron and replace it with 8 everywhere, and add --ignore-engines due to  qunitjs/qunit#1184.
This should not affect any functionality, normal regression only.
=> [EOSF-554] Update to Node.js version 8

addon/components/discover-page/component.js, addon/components/discover-page/template.hbs, addon/components/search-result/component.js
https://openscience.atlassian.net/browse/EOSF-771
If a preprint uses a branded domain that has a domain redirect enabled it should not use an osf url.  Instead, it should take the user to the branded domain (ex `engrxiv.org/guid` instead of `osf.io/preprints/engrxiv/guid`)
- Pass a filtered list of providers that are branded and redirect to the search-result component
- Update hyperlink function to check if any identifiers match a filtered provider's domain
If none of the identifier's match a branded domain, then it will use an osf url like before.
<hr>
(the preprint does not have an identifier that uses a branded domain, so it just uses the standard osf url)
<hr>
(this one has an identifier that uses a branded domain though, so it will have a url that points towards that instead)
<hr>
To …
=> [EOSF-771] Branded domain redirects

addon/components/discover-page/component.js
https://openscience.atlassian.net/browse/EOSF-667
To change the filter to accept multiple types of publications.
Change the query to use `terms` instead of `term` in preparation for accepting a list of publication types.
Since this is changing a part of the filter, please be sure to check that preprints, thesis, and registries still show up as expected.
=> [EOSF-667] Change filter to accept 'thesis'

addon/components/search-result/component.js
https://openscience.atlassian.net/browse/EOSF-836
In the search results, use an identifier link that contains a matching domain, regardless of the protocol.
Match based on domain instead of entire origin.
Make sure search results use the branded domain when the provider's domain uses https.
=> [EOSF-836] use branded domains in preprint search results regardless of protocol

addon/instance-initializers/ember-osf.js
Multiple people consuming the ember-osf app eventually get an error when using the built-in translating engine because it currently assumes the existence of theme providers.
=> Add fallbacks for when no provider is available or preprintWord never resolves

addon/components/discover-page/component.js
https://openscience.atlassian.net/browse/EOSF-649
Allow branded preprints to use the attribute `shareSource` in share queries on discover page.
Instead of just grabbing all preprints from share staging, there is a filtered list created from the provider list from share. All osf providers are filtered by their `shareSource` if they have one, all external preprint services should display the same results on any osf staging.
The `shareSource` for a `preprint_provider` must be populated for this change to be visible.
=> Feature/Use shareSource in discover page share query [EOSF-649]

addon/components/new-navbar-auth-dropdown/template.hbs, addon/components/new-osf-navbar/template.hbs
https://openscience.atlassian.net/browse/EOSF-736
To change the format of the ember-osf-navbar to match changes done to the osf navbar.
Change some of the buttons to be links with the role of button.  
Changes to use the new osf-style are done in a separate PR.
For testing this, please make sure that the navbar matches the osf side for consistency.
=> [EOSF-736] Change format of navbar

addon/components/file-renderer/component.js
https://openscience.atlassian.net/browse/EOSF-769
Quickfiles will need to have the ability to change versions.  Part of this is to show a different version in the mfr renderer when needed.  The purpose of this PR was to add a new property to the file renderer that handles versions being passed through.
Added a new property that watches for if a version is being passed through.  If there is a version, the url will update to append the version query parameter to the end of the mfr url.
=> [EOSF-769] Update file-renderer to take version

CHANGELOG.md, addon/components/new-osf-navbar/template.hbs, addon/const/service-links.js, addon/helpers/build-secondary-nav-links.js, addon/locales/en/translations.js
To add 'My Quick Files' link to the ember-osf navbar and to fix the 'Search' button to take the user to the search page instead of dropdown the search box.
- Add quickfiles to the navbar and translate files
- Change the search button into a link that goes to the search page
=> [EOSF-823] Add 'My Quick Files' link to navbar and fix 'Search' link

addon/components/file-browser/template.hbs
To fix the wording on the info modal for the file-widget.
Updated the wording for the info modal.
=> [EOSF-711] Fix file-browser dialog text

addon/components/file-browser-item/component.js, addon/components/file-browser-item/template.hbs
Make it possible to `ctrl+click` and `cmd+click` on file links to open a new tab.
- Added conditional to the ember click function to determine if `ctrl` or `cmd` keys were clicked on a link
- Added `preventDefault='true'` on the file links to prevent it from loading the file on the current and new tab on `cmd/ctrl+click`.
=> [EOSF-711] Add cmd/ctrl+click to open file in new tab

CHANGELOG.md, bower.json, package.json, yarn.lock
https://openscience.atlassian.net/browse/EOSF-767
Make ember-metrics and ember-toastr dependencies.
* Moved ember-metrics and ember-toastr to dependencies.
* Updated to ember-toastr@1.7.0
* Added toastr to package,json dependencies
* Removed toastr from bower.json
Make sure this doesn't break anything! ;)
=> [EOSF] make ember-metrics and ember-toastr dependencies

addon/components/discover-page/component.js
https://openscience.atlassian.net/browse/EOSF-882
Allow Registries discover page to return results once again
Handle case where themeProvider is not set.
Make sure this doesn't break Preprints
=> [EOSF-882] fix discover page for Registries

addon/components/discover-page/component.js
https://openscience.atlassian.net/browse/EOSF-777
Preprints had a small problem where initial query params would not be respected, and instead default query would take place when the page is first loaded. After investigating, it seems that the first query (before queryParams are 'noticed') takes longer to resolve than the subsequent computed queries, so its results are the last to be returned and are the ones displayed to the user.
This change makes it so, regardless of order of resolution, only requests with queries that match the query composed by the currently selected (or passed) filters will updated the results. 
Added safeguard that escapes update of results on query mismatch (between the one sent and the one currently selected). Should also help reduce flashing of results when …
=> [EOSF-777] Make sure results always match latest (and initial) filters selected

addon/models/file.js
https://openscience.atlassian.net/browse/EOSF-770
Remove the credential check on the Ajax call getting file contents.  Currently erroring on staging2.
=> [EOSF-770] Remove credential check on ajax call to get file contents

addon/components/file-version/component.js, addon/components/file-version/style.scss, addon/components/file-version/template.hbs, addon/styles/addon.scss, config/environment.js, package.json, tests/dummy/app/routes/application.js, tests/dummy/config/environment.js, tests/integration/components/file-version/component-test.js, yarn.lock
https://openscience.atlassian.net/browse/EOSF-769
To alter the file-version widget to include necessary information for the file-detail page.
Changed some of the data being sent through and added fields to the table for `Date`, `Download Count`, `MD5`, and `SHA2`.
Please be sure to check that the right information is being used in cases where there are multiple file versions.
In cases where there are multiple versions, the version currently selected is not clickable.  Please make sure that the versions clickable change based on what's selected.
=> [EOSF-769] File-version widget

CHANGELOG.md, addon/models/file.js
Currently when a user clicks on their own editable file and uses the editor, the Ajax call uses the basic download link associated with the file to get the contents.  Because of this, the Ajax call is acting as a theoretical download and is adding to the download count unnecessarily.  The purpose of this PR is to add more parameters to the Ajax call so that this doesn't happen.
Update the Ajax call to getContents of the file to use `redirect = true` and `mode='render'`.
None
https://openscience.atlassian.net/browse/EOSF-770
=> [EOSF-770] Update getContents() function for files

CHANGELOG.md, addon/components/file-browser-item/component.js, addon/components/file-browser-item/style.scss, addon/components/file-browser-item/template.hbs, addon/components/file-browser/component.js, addon/components/file-browser/style.scss, addon/components/file-browser/template.hbs, addon/components/file-version/template.hbs, addon/styles/addon.scss, addon/utils/outside-click.js
There are some basic styling and functionality errors on Quick Files.  This PR does a lot of small changes through the `file-browser`, file-browser-item` and `file-version` files, as well as adds a util function.
Added styling for some basic issues: 
- Height of the border on the `share link` column on the file-browser widget (to fix border not spanning the whole height of the header)
- Add CSS hack to position header elements over their represented columns
- Fix the width of the share popover to have a min-width.  This will prevent the popover from rendering small and expanding when guids load.
- Change position of the share button to have a margin off of the bottom of the row
- Change the formatted time to have `AM/PM` values instead of `am/pm`
- Fix the classes for the progress bar …
=> Changes to styling and functionality for Quick Files

addon/components/file-browser/component.js
Add properties to file-browser to control select behavior.
* Add properties to disable multiple select and unselect.
* Add property to open file on select.
Default values retain original behavior. Need to set these when calling the file browser.
https://openscience.atlassian.net/browse/EOSF-711
=> [EOSF-711] Add properties to file-browser to control select behavior

addon/components/dropzone-widget/component.js
The dropzone widget is currently trying to process files before queueing them.  This is causing issues when trying to upload files.
Add `autoQueue: false` when uploading a file.
None.
=> Fix dropzone queue error

CHANGELOG.md, addon/components/file-browser/component.js
Allow specification of pre-selected file in file-browser.
Added property to specify selected file.
Should not select any file/behave normally when this property is not set (e.g. on user-quickfiles).
https://openscience.atlassian.net/browse/EOSF-711
=> [EOSF-711] Feature/allow specifying a preselected file

CHANGELOG.md, addon/components/osf-footer/style.scss, addon/styles/addon.scss
Currently, footer styles are being defined in individual projects.  This should be avoided if we can centralize the styles with the actual footer itself in ember-osf.
Add style.scss file that has footer styles to match the regular OSF.
https://openscience.atlassian.net/browse/EOSF-913
=> [EOSF-913] Add footer styles

CHANGELOG.md, addon/helpers/build-secondary-nav-links.js, tests/unit/helpers/build-secondary-nav-links-test.js
When users are logged out, the Quickfiles navbar is different from the OSF style navbar.  
- Remove `Browse` from navbar
- Switch position of `Support` and `Donate` on navbar
https://openscience.atlassian.net/browse/EOSF-919
=> [EOSF-919] Change navbar to match OSF

CHANGELOG.md, addon/components/file-editor/template.hbs
The editor on the file-detail page currently shows a print margin when using the editor in full width.  There should not be a margin shown in any case.
- Add `showPrintMargin:false` on the ember-ace editor to remove the margin
https://openscience.atlassian.net/browse/EOSF-922
=> [EOSF-922] Remove print margin on ember-ace editor

addon/components/osf-footer/template.hbs
The footer currently uses an unnecessary class that adds a large top-margin.  We should remove this class from the footer to make the styling better.
Remove class from footer.
https://openscience.atlassian.net/browse/EOSF-913
=> [EOSF-913] Remove class from footer

addon/components/file-browser/style.scss, addon/components/file-browser/template.hbs
Fix the case where drop overlay persists when you cancel dropping a file.
* Added a dragleave handler
* Made drop overlay persistent and click-throughable to avoid flashing
Drop overlay should no longer persist when canceling a drop
https://openscience.atlassian.net/browse/EOSF-921
=> [EOSF-921] fix persistent drop overlay

CHANGELOG.md, addon/components/file-browser-item/component.js, addon/components/file-browser/component.js, addon/components/file-browser/template.hbs
To add analytics to the file-browser items for Quick Files.
Add analytics to: 
- Share link click
- Download from user who doesn't own
- Download as zip from user who doesn't own 
- Upload success
https://openscience.atlassian.net/browse/EOSF-873
Related to ember-osf-web https://github.com/CenterForOpenScience/ember-osf-web/pull/31
=> [EOSF-873] Add analytics to file items for Quick Files

addon/components/donate-banner/component.js
The donate banner currently has an end date of `2018`.  This should be changed.
None
=> Fix donate banner's end date

CHANGELOG.md, addon/components/file-browser-item/component.js, addon/components/file-browser-item/template.hbs, addon/components/file-browser/component.js, addon/components/file-browser/template.hbs, addon/utils/outside-click.js, tests/integration/components/file-browser-item/component-test.js
To keep the share button visible and consistent on all screen sizes, it should be moved to the toolbar with the other options.
Moved the share button and functionality from the `file-browser-item` component to the `file-browser`.  
https://openscience.atlassian.net/browse/EOSF-928
=> [EOSF-928] Move share button to toolbar

addon/components/file-browser/template.hbs
Restrict drop zone to file list and allow id customization
* Moved drop zone to just include file list.
* Added ability to customize id of drop zone
* Make sure dropping is restricted to file list
* When `dropZoneId` id not specified, should revert to ember-assigned unique id.
https://openscience.atlassian.net/browse/EOSF-921
=> [EOSF-921] Restrict drop zone to file list and allow id customization

CHANGELOG.md, addon/helpers/build-secondary-nav-links.js, tests/unit/helpers/build-secondary-nav-links-test.js
Support is currently not being shown on the Quickfiles navbar.  It should match what's shown on the OSF navbar.
Add Support button to the navbar.
https://openscience.atlassian.net/browse/EOSF-918
=> [EOSF-918] Add Support to the navbar

CHANGELOG.md, addon/components/file-browser/template.hbs
To change the rename button to be blue instead of green on the file-browser component.
Changed the color.
https://openscience.atlassian.net/browse/EOSF-927
=> [EOSF-927] Change rename button to be blue on file-browser

CHANGELOG.md, addon/components/file-browser/component.js
Quick Files will currently display an unreadable error message when trying to upload the same file twice.  We should fix the error message to actually be readable as well as copy behavior on the OSF (show upload progress bar without any messages or changes to the original file)
- Changed the error message to show `response.message`, which will display a proper error message instead of `[Object object]`
- Removed `?kind=file` from the file path if there is a conflicting file upon upload
<i>Upload warning messages will be discussed for a later release.</i>
https://openscience.atlassian.net/browse/EOSF-917
=> [EOSF-917] Fix error when uploading file twice

addon/components/file-browser/template.hbs
The 'Download as zip' button was mistakenly moved and will now only appear whenever there are items selected.  The button should only display if there isn't anything selected.
Move the 'Download as zip' button to where it's supposed to be.
https://openscience.atlassian.net/browse/EOSF-927
=> [EOSF-927] Fix position of 'download as zip' button

CHANGELOG.md, addon/components/file-browser/style.scss, addon/components/file-browser/template.hbs
On the file-detail page the scrollbar for the file-browser widget goes beyond the limits of the list.  The scrollbar should only be as tall as the parent it's in.
- Added conditional to fix `margin-bottom` on above element
On the file-detail page (small view)
On the main page (large view)
https://openscience.atlassian.net/browse/EOSF-929
=> [EOSF-929] Fix scrollbar on file-browser

addon/components/file-browser-item/component.js, addon/components/file-browser/component.js
In response to fixes done to https://github.com/CenterForOpenScience/ember-osf-web/pull/36, add query params to the openFile function to determine what view to go to.
Added query params or pass `view/revision` values.
https://openscience.atlassian.net/browse/EOSF-909
https://github.com/CenterForOpenScience/ember-osf-web/pull/36
=> [EOSF-909] Add query params to openFile function

addon/components/file-version/component.js, addon/components/file-version/template.hbs
The copy buttons for SHA2 and MD5 currently aren't working on the revisions table.  This is because it is not getting a proper id when calling the copy function.  
Pass the copy function a properly concatenated string for the id.
https://openscience.atlassian.net/browse/EOSF-936
=> [EOSF-936] Fix functionality for copy buttons on revision table

CHANGELOG.md, addon/components/dropzone-widget/component.js
Users currently are getting an error when trying to upload a file in Safari.
Added a conditional to check between `items` (for chrome) and `files` (for safari).
https://openscience.atlassian.net/browse/EOSF-939
=> [EOSF-939] Fix drop error on safari

addon/components/dropzone-widget/component.js, addon/components/file-browser/template.hbs
Make file browser upload button functional again.
Configure dropzone to make elements with .dz-message class clickable.
Make sure upload button works.
https://openscience.atlassian.net/browse/EOSF-921
=> [EOSF-921] Make file-browser upload button functional again

CHANGELOG.md, addon/components/file-browser-item/template.hbs, addon/components/file-browser/template.hbs
To hide and show specific columns in the `file-browser` table at certain screen sizes.
Changed which columns are displayed at certain sizes.
- Show all columns at large/xl sizes
- Only show name/size/modified at md
- Only show name/modified at sm
- Remove all except name at xs
https://openscience.atlassian.net/browse/EOSF-924
=> [EOSF-924] Change when table columns are displayed in file-browser table

CHANGELOG.md, addon/models/preprint-provider.js
There is soon going to be a flag that will return a boolean value in the case that a provider has highlighted subjects.  In order to make it easier in the future to access, there should be an alias in the provider model that will have the value ready.
- Add an alias in the provider model that returns the value of the `has_highlighted_subjects` flag
https://openscience.atlassian.net/browse/EOSF-884
=> [EOSF-884] Alter provider model to check for highlighted subjects

CHANGELOG.md, addon/components/dropzone-widget/component.js, addon/components/file-browser/component.js, addon/components/file-browser/style.scss, addon/components/file-browser/template.hbs
The dropzone widget is currently not clickable on staging preprints and quickfiles.
Make the things clickable (and add a bit of styling)
https://openscience.atlassian.net/browse/EOSF-951
=> [EOSF-951] Fix clickability on dropzone widget

CHANGELOG.md, addon/models/preprint.js
Currently, preprint DOI link on preprint detail page could fail to resolve when the DOI is being minted. This PR shows a prompt message and shows DOI as plain text while the DOI is being minted.
In `model/preprint.js`, a new attribute `preprintDoiCreated` is added to the model to fetch the apiV2 `preprint_doi_created` field.
Also updated the changelog.
None
https://openscience.atlassian.net/browse/EOSF-879
=> [EOSF-879] Update preprint to show alert when DOI is being minted.

CHANGELOG.md, addon/components/dropzone-widget/component.js, package.json, yarn.lock
Only reload Dropzone when clickable attribute changes
* Refactor to only reload Dropzone when clickable attribute changes (already noted in CHANGELOG.md)
* Also, properly handle Dropzone enable and disable
Refactor based on recommendation from https://www.emberjs.com/deprecations/v2.x/#toc_code-didreceiveattrs-code-and-code-didupdateattrs-code-arguments
Dropzone in Preprints lets you upload again
N/A
=> Only reload Dropzone when clickable attribute changes

CHANGELOG.md, addon/serializers/osf-serializer.js
Rename `meta.total` to be more descriptive to help avoid confusion.
Changes `meta.total` to `meta.total_pages` in osf-serializer.
Will need to rename usage of this in preprints.
https://openscience.atlassian.net/browse/EOSF-960
=> [EOSF-960] rename meta.total to meta.total_pages

addon/components/validated-input/style.scss, addon/styles/addon.scss
This PR is related to https://github.com/CenterForOpenScience/ember-osf-preprints/pull/479. This add css styles to style.scss for `validated-input` component.
Added css styles to `validated-input/style.scss`.
None.
https://openscience.atlassian.net/browse/EOSF-844
=> [EOSF-844] Change css styles

CHANGELOG.md, addon/models/preprint-provider.js
To change the preprint-provider model's `hasHighlightedSubjects` alias to point to the right place.
Remove `data` from beginning of path for `hasHighlightedSubjects`.
https://openscience.atlassian.net/browse/EOSF-884
=> [EOSF-884] Change path of alias for highlighted_subjects for provider models

CHANGELOG.md, addon/adapters/osf-adapter.js, addon/models/osf-model.js, addon/services/file-manager.js, addon/utils/load-relationship.js, package.json, tests/unit/models/osf-model-test.js, yarn.lock
Move the [`queryHasMany` helper from ember-osf-reviews](https://github.com/CenterForOpenScience/ember-osf-reviews/blob/develop/app/services/store.js#L21) to ember-osf. Provides a way to query relationships without going through ember-data, which sometimes decides it has all the data it needs and doesn't make the request.
- Add `queryHasMany` method to `osf-model`
- Allows querying relationships with custom query params and ajax options
e.g. `user.queryHasMany('nodes', { filter: { title: "My title!", public: true } })`
- Remove ember-data-has-many-query
Code that uses `model.query()` has to be updated to use `model.queryHasMany()`. In most cases, it's a drop-in replacement, but I didn't want to replace it silently in case someone tries to query a `belongsTo` or somehow depends on …
=> [MOD-176][Feature] Replace has-many-query with queryHasMany

CHANGELOG.md, addon/components/dropzone-widget/component.js
Currently for quickfiles, uploading multiple files by drag'n'drop is not allowed and would show "Cannot upload multiple files". However, this is not the case when user clicks the "upload" button and select multiple files to upload. This PR fix this problem by not allowing users to select multiple files for upload.
Dropzone.js handles drag'n'drop upload differently than clicking the "upload" button for upload. Therefore, there is not an event handler that we can override to prevent multiple uploads through clicking the "upload" button. However, we could remove the "multiple" attribute from the hidden `<input>` element Dropzone uses, thus preventing users from selecting multiple files. And that is what is done in this PR.
None.
https://openscience.atlassian.net/browse/EMB-60
=> [EMB-60] Prevent user from selecting multiple files when clicking upload button.

addon/components/file-browser/component.js
Handle authentication failure error responses on file upload in file-browser component.
Coalesce all possible response formats to find error message, starting with most specific.
Go to quick files, open another window and log out of the OSF, attempt a file upload. You should get a nice informative error message instead of `[object Object]`.
https://openscience.atlassian.net/browse/EMB-84
=> [EMB-84] Get upload error message by coalescing all possible response formats

CHANGELOG.md, addon/components/project-selector/style.scss
Add styling to show when a button is selected on the project selector.
Change the background-color and color of selected buttons.
There is only the main CSS styling change to the sheet, which should change the color of the button and the font on select.
https://openscience.atlassian.net/browse/EMB-17
=> [EMB-17][ember-osf] Add button style on select for project selector

addon/components/file-browser/template.hbs
Temporarily remove move button in file browser.
Wrapped move button with HTMLBars comment.
Move button should never appear.
https://openscience.atlassian.net/browse/EMB-101
=> [EMB-101] Temporarily disable file browser move button

addon/components/file-browser/component.js, addon/components/file-browser/style.scss, addon/components/file-browser/template.hbs
Disable upload button while a file is uploading.
* add isUploading computed based on whether the uploading list is not empty
* use it to disable the upload button
Make sure you can't click the upload button while an upload is in progress.
https://openscience.atlassian.net/browse/EMB-105
=> [EMB-105] Add isUploading computed and use to disable upload button

addon/components/file-browser/component.js
Have every item created in quickfiles have a guid.
Attempt to generate guid as a asynchronous side effect to having a successful file upload.
https://openscience.atlassian.net/browse/EMB-111
=> [EMB-111] Always attempt to create a file's guid on upload

addon/components/validated-input/component.js, addon/components/validated-input/template.hbs
Currently, when the user manually edits the "Original publication date" field on preprint submission/edit page, the value of the property does not change when the element loses focus. This PR fixes the problem.
A `focusOut` event handler is added to parse and set the value from manual input.
For an existing preprint, make sure that when you manually change date value in the "Original publication date" field (not using datepicker) and then click "save", the change is reflected in the preprint detail page.
https://openscience.atlassian.net/browse/IN-78
=> [IN-78][Emberosf] Fix focusOut issue

CHANGELOG.md, addon/models/preprint-provider.js
`facebook_app_id` was recently added to the `preprint_provider` model in osf.io.  We should add it to the `preprint-provider` model in ember-osf to use it for sharing on branded preprints.
- Added `facebookAppId` field to `preprint-provider` model
This shouldn't affect anything other than adding a field to the model.  
https://openscience.atlassian.net/browse/IN-31
=> [IN-31][Ember-OSF] Add facebookAppId to preprint-provider model

CHANGELOG.md, addon/components/discover-page/component.js, addon/services/current-user.js, tests/unit/services/current-user-test.js
Fix current issue where share elasticSearch returns inconsistent
result ordering.
See here for more details
https://www.elastic.co/guide/en/elasticsearch/reference/current/consistent-scoring.html#_scores_are_not_reproducible
See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html for suggested solution.
Modify searchUrl to use currentUserId as preference custom string in case user
is logged in. Otherwise, use a random string.
This ticket affects the preprints discover/search page.
Test this within the developer console, networks tab:
- Clear the network tab
- Upon searching a term, check the elasticSearch requests to see if the preference
URL parameter was added and looks something like this (in chrome console)
i) logged-in user: …
=> [IN-103][Ember-OSF] Use currentUserId for ElasticSearch preference

addon/components/citation-widget/component.js, addon/components/citation-widget/template.hbs, addon/locales/en/translations.js
Fix issues identified by QA for citation widget.
* Add placeholder text to citation widget
* Fix spacing for citation widget
* Move some plain text to the translation file
* Reorganized the file a bit/added some whitespace for readability
**Before:**
**After:**
* There should be a placeholder in the citation widget on preprints now.
* The citation should now show unless a citation style has been selected.
* The text associated with the widget should all appear normal (I moved the text to a translation file).
https://openscience.atlassian.net/browse/IN-71
=> [IN-71][Ember-OSF] Fix issues identified by QA for citation widget

addon/components/citation-widget/component.js
Allow contributors to generate different citations before their preprint is public.
* Add authentication to the citation request.
* Ordered imports like "standard library imports, third party imports, local application imports"
Should not change the behavior for logged out users.
Authors should be able to generate different citations before their preprint is public.
https://openscience.atlassian.net/browse/IN-71
=> [IN-71][Ember-OSF] Add authentication to citation request

addon/components/citation-widget/component.js
Selecting a citation for a preprint shouldn't 401.
* Add authentication to the select citation request
* Remove authentication from the search request since it doesn't need authentication
Selecting a citation for a preprint shouldn't 401 -- specifically a pending pre-moderation preprint where the related project is private.
https://openscience.atlassian.net/browse/IN-71
=> [IN-71][Ember-OSF] private project

CHANGELOG.md, addon/adapters/osf-adapter.js
Bump osf API version from `2.4` to `2.6`
OSF API version `2.5` deprecated `subjects_acceptable` field on the preprint_provider endpoint.
OSF API version `2.6` deprecated the `/v2/taxonomies/`.
Update the osf adapter to use version 2.6 of the api.
https://openscience.atlassian.net/browse/IN-137
=> [IN-137][Ember-OSF] Use version 2.6 of osf API

CHANGELOG.md, addon/components/new-navbar-auth-dropdown/component.js, addon/components/new-navbar-auth-dropdown/template.hbs, addon/components/new-osf-navbar/template.hbs
osf-style is now adding `flexbox` to the navbar styles from [this PR](https://github.com/CenterForOpenScience/osf-style/pull/111).  The current ember-osf navbar should change in order to reflect these new styles.
- Move the `navbar-toggle collapsed` button to right of the other elements in its container
- Added `secondary-nav-dropdown` class to the `new-navbar-auth-dropdown` component
- Changed classes and element tags to match styles needed for long name truncation
This should be tested with https://github.com/CenterForOpenScience/osf-style/pull/111 which adds the styles to the navbar
- Relates to https://github.com/CenterForOpenScience/osf.io/pull/8163
- Will need to be updated to use newest version of osf-style after https://github.com/CenterForOpenScience/osf-style/pull/111 is merged …
=> [IN-234][Ember-OSF] Fix navbar to take in new osf-style changes to navbar

addon/components/new-navbar-auth-dropdown/component.js, addon/components/new-navbar-auth-dropdown/template.hbs
Long names in the navbar are still not flexing properly.  This PR should fix that.
- Removed wrapper from component
- Added `li` tagName to the dropdown being generated with all of the necessary classes
- Changed button to `a` tag
- Added `<li>` to sign-in/sign-up button section (needed since the component no longer has an `li` wrapper)
This should fix the issues with flexing on reviews/registries.  When there's a name longer than the space given it should break off with `...` ellipses at the end.  It shouldn't run off the page or break onto a new line.
This should also fix the issue of positioning in the navbar.  Before, the name would float just a bit higher than the rest of the navbar text.  This should keep the text inline with everything else. …
=> [IN-234][Ember-OSF] Updated fix for long names in navbar

CHANGELOG.md, addon/components/discover-page/component.js
As part of the fix to remove observers from ember@2.18 registries.  
The `activeFilters.type` property should be reset from the ember-osf app to resolve glimmer errors showing up on registries.
- Reset `activeFilters.types` when the provider is changed to something other than `OSF`
This will work with the Registries PR (https://github.com/CenterForOpenScience/ember-osf-registries/pull/58).  It should help to make the type facets on Registries work like expected again.
https://openscience.atlassian.net/browse/IN-90
=> [IN-90][EmberOSF] Clear types filter on registries provider change

addon/components/new-navbar-auth-dropdown/template.hbs
The sign-up and sign-in buttons are different sizes in the navbar.  They should both be the same.
- Added an inline `line-height` property to the sign-up button to make it the same size as the sign-in button.  This is a temporary fix and will need to be removed when ember-osf and osf are updated to use the newest osf-style.
There shouldn't be any side-effects.  The button should now be the same size as the other button on the navbar.
Before:
After:
None
=> [EOSF] Fix sign-up button size

CHANGELOG.md, addon/adapters/moderator.js, addon/models/moderator.js, addon/serializers/moderator.js, app/adapters/moderator.js, app/models/moderator.js, app/serializers/moderator.js, test-support/factories/moderator.js, tests/unit/adapters/moderator-test.js
Allow preprint providers to add and remove moderators using the moderation app.
* Add moderator model, serializer, and adapter.
Should be covered by testing the Reviews side.
https://openscience.atlassian.net/browse/IN-6
=> [IN-6][Ember-OSF] Add model for moderator

CHANGELOG.md, addon/components/navbar-auth-dropdown/component.js, addon/components/navbar-auth-dropdown/style.scss, addon/components/navbar-auth-dropdown/template.hbs
The branded navbar's styling doesn't match what is seen in ember-osf and osf.io
- Add some styling to `btn-link` to remove color changes that shouldn't be seen on branded domains
- Change classes and id's in branded navbar to match what's needed in osf-style
- Add 'secondary-nav-dropdown' class to `navbar-auth-dropdown`
This should make the branded navbar act the same way as the navbar on ember-osf apps and osf.io.  
- It should cut off long user names and prevent breaking to a new line
- It should also keep cutting the name as the screen gets smaller
- Because this is branded, it should also keep using the old styles that are provider specific
** Note**
This should be used with the change to ember-osf-preprints: 
https://github.com/CenterForOpenScience/ember-osf-preprints/pull/567 …
=> [IN-235][Ember-OSF] Fix styling and format of branded navbar

CHANGELOG.md, addon/components/maintenance-banner/template.hbs
Fix missing translation in banner on Reviews and Registries.
* Remove period from end of translation string
Must have maintenance banner up to test.
Will be created shortly
https://openscience.atlassian.net/browse/IN-311
=> [IN-311][EmberOSF] Remove period from end of translation string

addon/components/new-osf-navbar/component.js, addon/components/new-osf-navbar/template.hbs, addon/const/service-links.js, addon/services/current-user.js, index.js, package.json, tests/unit/services/current-user-test.js, tests/unit/services/file-manager-test.js, yarn.lock
Allow the use of waffle in ember-osf apps, and update the navbar to have a link to the institutions landing page when that flag is turned on.
- Add ember-feature-flags
- Use ember-feature-flags and the current-user service to grab and use waffle flags/switches.
https://openscience.atlassian.net/browse/EMB-259
=> [EMB-259] Waffling + Institutions nav

CHANGELOG.md, addon/components/discover-page/template.hbs, addon/components/faceted-search/template.hbs
This is the second of two PRs (the first PR is [here](https://github.com/CenterForOpenScience/ember-osf-preprints/pull/492)) for the preprint discover page to get whitelisted SHARE providers from /preprint_providers endpoint of API V2.
New parameters are added to `discover-page` and `faceted-search` components to allow passing of the whitelist down to `search-facet-provider` component.
None
https://openscience.atlassian.net/browse/IN-70
=> [IN-70][Ember-OSF] Add whitelist functionality for preprint discover page

addon/components/scheduled-banner/template.hbs
Make banner unclickable if no custom link
Add check for link.
Simply check if the banner is clickable only when a link is provided.
[[IN-165]](https://openscience.atlassian.net/browse/IN-165)
[[IN-250]](https://openscience.atlassian.net/browse/IN-250)
=> [[IN-250]][EmberOSF] Make banner unclickable if no custom link

CHANGELOG.md, addon/components/scheduled-banner/component.js, addon/components/scheduled-banner/style.scss, addon/components/scheduled-banner/template.hbs
Fix inconsistent banner look on ember apps.
h/t @baylee-d for helping me understand and fix the CSS issues
- Fix banner styles
- Center the banner image
Make sure the banner is centered.
Please try different sizes heights to make sure larger banners display right.
[IN-159](https://openscience.atlassian.net/browse/IN-159)
=> [IN-159][EmberOSF] Center banner img; add max height

CHANGELOG.md, package.json, tests/dummy/config/environment.js, yarn.lock
as part of GDPR compliance efforts, `anonymizeIp: true` allows
the sender IPs to be anonymized.
- Update config to set `anonymizeIp: true`
- Point to fork to allow setting GA configs.
In case GA is enabled on staging environments, you can verify this flag is set by looking at the GA requests in the console (filter by `collect`)
[IN-338](https://openscience.atlassian.net/browse/IN-338)
=> [IN-338][Ember-OSF] GA anonymize sender ip

CHANGELOG.md, addon/components/search-result/component.js, addon/components/search-result/style.scss, addon/components/search-result/template.hbs
Registrations on the discover page are currently shown without any indication of what parent projects/components they belong to.  This should be changed to match what's on the OSF.
- Use lineage lists from SHARE to show the titles of parent components/projects
This currently will not work with registrations since the info isn't being passed through from SHARE.  This will work as soon as that data is available.
The styling was made to look like SHARE and should end up looking like this:
https://openscience.atlassian.net/browse/IN-32
=> [IN-32][EmberOSF] Add parent ancestry to discover page components

CHANGELOG.md, addon/components/cookie-banner/component.js, addon/components/cookie-banner/style.scss, addon/components/cookie-banner/template.hbs, app/components/cookie-banner/component.js, tests/integration/components/cookie-banner/component-test.js
This will add a new cookie-banner component to EmberOSF.  It will sit on the bottom of the page it's included on and float there.  There is only an accept button and when it's clicked it will add a cookie to the user's browser to determine not to display the banner on the site.
- Added `cookie-banner` component and test
Viewing the page as a non-logged in user:
Clicking the accept button will remove the banner from the page:
A logged-in user won't see the cookie banner on the screen:
There are a few conditions that should be tested:
- If the user is logged out, the banner will show
- If the user is logged in, the banner won't show
- If the user clicks `accept` the banner should disappear and won't show up again (unless the cookie is manually deleted)
The banner will show up on the bottom …
=> [IN-234][EmberOSF] Add cookie-banner component

addon/components/file-renderer/component.js, addon/models/preprint-provider.js, config/backends.json
Allow toggling hypothesis based on preprint provider setting.
* Start hypothesis in file renderer if allowCommenting is true for the current preprint provider
* Add allowCommenting to preprint provider model
This has already been tested via 0.119.0 preprints release but we need to add these changes to an actual ember-osf release.
https://openscience.atlassian.net/browse/IN-170
Replaces #377 
Should go in before the 0.120.0 release so that we don't have the preprints changes without the ember-osf changes.
=> [IN-170][ember-osf] Hypothesis toggle

addon/components/discover-page/component.js
Clicking "Clear filters" doesn't always clear all the filters. Leaves one or two sometimes. (Have not found a clear way to reproduce this). [See gif](http://g.recordit.co/htRl75GH8h.gif)
* Make a copy of queryParamsState as to not modify the original value
[See stack overflow answer for better explanation](https://stackoverflow.com/questions/6612385/why-does-changing-an-array-in-javascript-affect-copies-of-the-array)
Test that selecting filters, clearing the filters, then selecting more filters and clearing those works properly. This issue is a little intermittent so I would try it several times.
https://openscience.atlassian.net/browse/IN-350
This change is necessary for preprints 0.120.0 and registries 0.9.0.
=> [IN-350][Ember-OSF] Make a copy of queryParamsState as to not modify the original value

addon/utils/discover-page.js
Registration type should show in search results.
* Get registration type from SHARE response
**Before**
**After**
Should make sure the registration type appears in search results.
https://openscience.atlassian.net/browse/IN-350
N/A
=> [IN-350][Ember-OSF] Get registration type from SHARE response

addon/components/cookie-banner/style.scss
To fit with requirements, this will update the cookie banner to be more responsive on small screens and mobile layouts.
- Made the margin size smaller between the text and button to reduce the amount of space that's used.
- On screens smaller than 500px, stack the text and button horizontally to keep the layout clean.
This primarily deals with CSS, so just testing that things move when they're supposed to.  When the screen size is 499px or smaller the button will move to a new line below the text.  The text will not be centered.  The button should be centered on its line.
https://openscience.atlassian.net/browse/IN-324
=> [IN-324][EOSF] Update cookie banner styling and responsiveness

CHANGELOG.md, addon/components/new-osf-navbar/template.hbs
On the non-branded navbar, `Add a Preprint` changes to just `Add` on small/mobile screen sizes. This doesn't happen on the branded navbar. We should try to keep it consistent between all screen sizes.
* Use `Add a Preprint` regardless of screen size
Make sure branded / non-branded links behave as expected
[[IN-392]](https://openscience.atlassian.net/browse/IN-392)
=> [IN-392][EmberOSF] Preprint link language consistency

CHANGELOG.md, addon/adapters/user.js, tests/unit/adapters/user-test.js
Need way to hit the search users endpoint. Allows the url to change depending on your query.
Used urlForQuery to modify how it searches depending on the presence of q query param. 
Add tests
None here, testing notes on preprints side ticket
https://openscience.atlassian.net/browse/IN-102
None
=> [IN-102][EmberOSF] Allow user search to use elastic endpoint

addon/authenticators/osf-cookie.js
Currently, `ember-osf` authenticator asks `/v2/users/me/` endpoint for current user's information. If the user is not authenticated, the endpoint returns a 401, which is not good.
Therefore, we change to using `/v2/` which would not return a 401 even if the user is not authenticated.
In `osf-cookie.js`, the endpoint of the AJAX request is changed to `/v2/`.
https://openscience.atlassian.net/browse/EMB-400
=> [EMB-400] Change the endpoint for the authenticator from `/v2/users/me/` to `/v2/`

addon/components/file-renderer/component.js, addon/components/file-renderer/template.hbs, tests/integration/components/file-renderer/component-test.js
Change the link `file-renderer` uses for rendering preprints.
https://openscience.atlassian.net/browse/EMB-412
=> [EMB-412][EOSF] Change link for rendering preprints.

CHANGELOG.md, addon/adapters/contributor.js, addon/adapters/preprint.js, addon/components/file-renderer/component.js, addon/components/old-file-browser/template.hbs, addon/locales/en/translations.js, addon/mixins/contributor-mixin.js, addon/models/contributor.js, addon/models/node.js, addon/models/preprint.js, package.json, tests/unit/mixins/contributor-mixin-test.js
This PR merges NPD branch into Chronos branch.
=> [EMB-535][EOSF][Chronos][NPD]Merge NPD changes to Chronos branch.

addon/models/user.js
This PR enables claiming of unregistered users.
A custom method `claimUnregisteredUser` is added to the user model.
https://openscience.atlassian.net/browse/EMB-519
=> [EMB-519] Add custom method to user model to allow claiming of unregistered users.

addon/mixins/osf-cookie-login-route.js, addon/utils/transition-target-url.js, app/utils/transition-target-url.js
Add "API Unavailable" page like this:
- Port the `transition-target-url` util from @CenterForOpenScience/ember-osf-web
- Modify `osf-cookie-login-route.js` to redirect to `error-no-api` route on network error.
- Make use of the new util so that upon redirection it keeps the url of the destination route.
NOTE: This implementation requires any apps using the `osf-cookie-login-route` mixin to have an `error-no-api` route defined. However for reviews app, that might need a refactor of how we check user permissions for reviews app, which I don't think worth the effort after poking around it for a bit. Therefore, if you go the reviews app when the API is down, it shows a blank page after this fix goes in.
See testing notes for the preprints ticket. …
=> [EMB-531][EOSF] Add "API Unavailable" message page.

testem.js
Dot reporter produces much friendlier output and is what we use in ember-osf-web.
Configure Testem to use the dot reporter.
n/a
n/a
See the nice output?
=> switch to testem dot reporter

addon/mixins/osf-cookie-login-route.js
In the previous implementation of this ticket, it seems that the `error` event handler in child routes will conflict will preempt the route redirection in the `catch` block of the `beforeModel` hook. Weird thing is that it only happens in a prod build but not a development build. This PR attempt to fix the problem by utilizing the `error` event handler in the route. See more below.
Instead of catching the error after returning the promise in the `beforeModel` hook and transition to a `error-no-api` route, we move the transition to the `error` handler. There are two benefits to this:
- `error` handler in the route catches error occurred in the lifecycle hooks, so it's equivalent to the catch block.
- It also catches errors bubbled up from child route's …
=> [EMB-531][EOSF] API unavailable message fix

addon/adapters/preprint-request-action.js, addon/adapters/preprint-request.js, addon/models/preprint-request-action.js, addon/models/preprint-request.js, addon/models/preprint.js, addon/serializers/preprint-request-action.js, addon/serializers/preprint-request.js, app/adapters/preprint-request-action.js, app/adapters/preprint-request.js, app/models/preprint-request-action.js, app/models/preprint-request.js, app/serializers/preprint-request-action.js, app/serializers/preprint-request.js, tests/unit/models/preprint-test.js
This PR adds two models, `preprint-request` and `preprint-request-action`, and their adapters and serializers. This is necessary for withdrawal-related functionalities to work on both the Reviews and Preprints app.
Models and serailizers changes are quite straightforward.
For the adapter for `preprint-request`, `urlForQuery` and `urlForCreateRecord` are overridded to construct the correct url.
Nothing to test for this PR specifically. See other PRs for testing notes.
https://openscience.atlassian.net/browse/IN-327
https://openscience.atlassian.net/browse/IN-328
=> [Preprint Withdrawals][EOSF][EMB-549][EMB-548][EMB-550][EMB-551] Add 'preprint-request' and 'preprint-request-action' model

addon/components/file-renderer/component.js
For preprints using non-US storage, the hypothesis postMessage is being blocked because the target domain does not match. This is because we are using the MFR URL from config (which is always the US MFR) instead of determining the MFR origin from the render link provided by the API.
* set hypothesis post message target domain based on render link
Need to make sure hypothesis loads for preprints using non-US storage.
https://openscience.atlassian.net/browse/ENG-381
To test this, you will need to update you local preprints to use this branch of ember-osf.
An easy way to do this is:
```
yarn upgrade @centerforopenscience/ember-osf@https://github.com/jamescdavis/ember-osf#set_hypothesis_post_message_target_domain_based_on_render_link
```
=> [ENG-381] set hypothesis post message target domain based on render link

addon/components/file-renderer/component.js
Need to bind `this` for `this.get('mfrOrigin')`.
* use arrow function for hypothesis postMessage
Make sure 
https://openscience.atlassian.net/browse/ENG-381
I tested this locally.
=> [ENG-381] fix: use arrow function for hypothesis postMessage

addon/adapters/chronos-submission.js
Change `adapters/chronos-submission.js` enable `PUT/PATCH` to chronos submission detail endpoint when there are no dirty attrs.
Override `urlForUpdateRecord()` to construct the correct url.
Override `updateRecord()` to send PUT/PATCH to endpoint when there's no dirty attrs.
https://openscience.atlassian.net/browse/ENG-650
=> change chronos-submission adapter

CHANGELOG.md, package.json
To ensure we are all using the same versions of node and yarn in development.
- `volta pin node@8.17.0`
- `volta pin yarn@1.21.1`
No testing necessary as this only affects development environments.
n/a
`yarn install` is failing on this repo with Node 10 so it must be pinned to Node 8 for now.
=> chore: pin with volta: node@8.17.0, yarn@1.21.1

addon/authenticators/osf-cookie.js, addon/services/current-user.js
For Sloan changes, we need waffles to apply to both logged in and logged out users.
- Move waffle setting outside of the current-user service in ember-osf
This should affect users in all apps that user `ember-osf`. Will affect preprints and reviews. Should apply any waffle flags that are applicable even if the user is logged in or out.
https://openscience.atlassian.net/browse/ENG-26
Should apply waffle flags regardless of the status of the user.
=> [ENG-26][Feature] Update ember-osf waffle to apply to logged-out users

addon/models/preprint.js
For future sloan changes, we'll need to add fields to the preprints model.
- hasCoi: `boolean`
- hasDataLinks: `boolean`
- hasPreregLinks: `boolean`
- dataLinks
- preregLinkInfo
- preregLinks
- conflictOfInterestStatement: `fixstring`
- whyNoData: `fixstring`
- whyNoPrereg: `fixstring`
`n/a`
https://openscience.atlassian.net/browse/ENG-1485
Double check that the models reflect the type needed. Fields represented by an array field or checkbox are an empty `attr` type.
Used this PR as a reference for fields: https://github.com/CenterForOpenScience/osf.io/pull/9280/files
=> [Feature] [ENG-1485] Add sloan fields to preprints model

addon/models/preprint-provider.js, addon/models/preprint.js
Update the model to have proper fields with string properties to accommodate `Not applicable`.
Update the following fields on the preprint model:
- `hasDataLinks`: `string`
- `hasPreregLinks`: `string`
Add `inSloanStudy` field on the preprint-provider model.
`N/A`
`N/A`
`N/A`
=> [Feature] Update preprint model to have string fields

addon/models/preprint.js
Currently, the `hasCoi` field of the preprint model does not allow null value, which is problematic because the backend may actually serialize `hasCoi: null`. Not allowing `hasCoi` field to be nullable also breaks the validation on the FE, as there is no way to tell whether the `hasCoi` field on the model has been set by the user.
Add `allowNull: true` to the boolean transform of the model.
=> [No Ticket] Set preprint hasCoi field to allow null value

CHANGELOG.md, addon/components/new-navbar-auth-dropdown/template.hbs, tests/integration/components/new-navbar-auth-dropdown/component-test.js
- This should fix the issue where logged out users see a broken gravatar in the preprints app
- fixed a bad `if` statement that was causing this issue (literal one character fix!)
- added test to make sure proper items are shown in authenticated/unauthenticated scenarios
- please make sure that the navbar looks correct and all the proper options are shown for authenticated sessions and unauthenticated sessions!
https://openscience.atlassian.net/browse/ENG-1504
- issue seemed to be from the broken `if` statement
- feel free to comment if the test could be better as well
=> [ENG-1504] Fix broken gravatar for logged out users

package.json, yarn.lock
To update some of our dependencies to fix security issues and just be more generally up to date.
- Bump `ember-cli-app-version` from 2.0.2 to 3.2.0
- Bump `ember-cli-htmlbars-inline-precompile` from 0.4.3 to 2.1.0
- Bump `sshpk` from 1.13.1 to 1.16.1
- Bump `lodash.merge` from 4.6.0 to 4.6.2
- Bump `atob` from 2.0.3 to 2.1.2
- Bump `fstream` from 1.0.11 to 1.0.12
- Bump `ember-ace` from 1.2.0 to 2.0.1
- Bump `ember-diff-attrs` from 0.2.1 to 0.2.2
- Bump `ember-font-awesome` from 3.0.5 to 3.1.1
- Bump `tar` from 2.2.1 to 2.2.2
`N/A`
`N/A`
`N/A`
=> [Updates] Bump dependency versions

addon/components/file-renderer/component.js, addon/components/file-renderer/template.hbs
Preprints on hypothes.is-enabled providers are showing irrelevant comments on Google Chrome.  We use two identifiers to link a preprint to its h.is comments: a unique fingerprint and the OSF url of the preprint.  A recent change[1] in Google Chrome has made it so that the h.is-initiating code no longer has access to the full url of the preprint.  It just gets the host.
This PR manually specifies the referrer-policy of the iframe to allow both the host and path through.  This is identical to the current behavior of Firefox, Safari, and Edge.
[1] https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default
Set the referrer-policy on MFR iframes to "no-referrer-when-downgrade".  This allows the page within the iframe to get both the origin and path of the calling …
=> [hotfix][ENG-2307] fix preprints/hypothes.is integration in Chrome

.github/workflows/CI.yml, addon/models/preprint.js, addon/serializers/osf-serializer.js, bower.json, package.json, yarn.lock
- Allow a preprint's metrics metadata to be serialized in the `apiMeta` property
- Normalize `findRecord` responses to include the response.meta into an `apiMeta` attribute so it can be used later in the app (specifically preprint's views/download metrics)
- this change is additive and doesn't change any existing user-facing behavior
https://openscience.atlassian.net/browse/ENG-23
- I've opted to store the response.meta object into the `apiMeta` attribute as this seemed like the easiest way to access the impact metrics for a given preprint. I looked at using store.findMetadataFor('preprint'), but it seems this is deprecated.
=> [ENG-23] Serialize meta for preprint findRecord

addon/const/service-links.js, package.json, yarn.lock
- Link users to new helpscout guides
- The "Support" link in the preprints navbar should now go to the new helpscout guides 
- Verify that the navbar link does indeed go to the helpscout page
[ENG-3657]
- This is to just change the link in the navbar. Other links going to the old help guides can stay for now, and will be revisited in the future
[ENG-3657]: https://openscience.atlassian.net/browse/ENG-3657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-3657] Change navbar support link to go to helpscout

addon/components/file-renderer/component.js
Fix hypothes.is comment linking on preprints by having parent window pass its own url to the iframe.  From commit msg:
```
* MFR overrides the hypothes.is annotator to send the parent window's
url. It had been doing this by calling `document.referrer` in the
child iframe, but to improve privacy browsers have started making
only the parent window's domain available to the child. The child
no longer has access to the full path.
```
From commit message:
```
To get around this, the parent window will now send along its full
url with the `startHypothesis` message it sends to the child
iframe. MFR has been updated to receive and store this url and to
use it to identify comments when submitting to the upstream
service.
```
Dev will test by submitting comments via Brave browser and making sure …
=> [ENG-3124] send parent window url in startHypothesis message

CHANGELOG.md, addon/components/discover-page/template.hbs, addon/components/file-renderer/template.hbs, addon/locales/en/translations.js
Fixes two accessibility problems in the preprints app.
1. Add a `title` to the mfr iframe in the file renderer.
2. Remove redundant aria-label on the discover page.
Just needs accessibility testing.
https://openscience.atlassian.net/browse/ENG-3164
https://openscience.atlassian.net/browse/ENG-3762
=> [ENG-3164] [ENG-3762] Two a11y fixes
